import type { PoolClient } from 'pg';
import { afterAll, beforeAll, describe, expect, it } from 'vitest';
import {
  actAs,
  closePools,
  inRolledBackTx,
  loadSeedIds,
  resetRole,
  sqlState,
  type SeedIds,
} from '../test/helpers';

// Exercises the policies generated by core.apply_domain_rls() on fixture tables.
// Every fixture lives in a migrator transaction that is rolled back.

const INSUFFICIENT_PRIVILEGE = '42501';

let ids: SeedIds;
beforeAll(async () => {
  ids = await loadSeedIds();
});
afterAll(closePools);

async function register(
  c: PoolClient,
  table: string,
  opts: {
    domain: string;
    modifyDomain?: string;
    insertOnly?: boolean;
    nodeColumns?: string[];
    audit?: boolean;
  },
): Promise<void> {
  await c.query(
    `insert into core.domain_table (tenant_id, table_name, domain_id, modify_domain_id, insert_only, node_columns)
     select t.id, $1::regclass, d.id, md.id, $3, $5
       from core.tenant t
       join core.domain d on d.code = $2
       left join core.domain md on md.code = $4
      limit 1`,
    [
      table,
      opts.domain,
      opts.insertOnly ?? false,
      opts.modifyDomain ?? null,
      opts.nodeColumns ?? null,
    ],
  );
  await c.query('select core.apply_domain_rls($1::regclass)', [table]);
  if (opts.audit ?? true) await c.query('select audit.enable($1::regclass)', [table]);
}

async function visible(c: PoolClient, who: string, table: string, col: string): Promise<string[]> {
  await actAs(c, 'app_rw', ids.user(who));
  const { rows } = await c.query<{ v: string }>(`select ${col} as v from ${table} order by 1`);
  await resetRole(c);
  return rows.map((r) => r.v);
}

async function tryAs(c: PoolClient, who: string, text: string, params: unknown[] = []) {
  await actAs(c, 'app_rw', ids.user(who));
  const state = await sqlState(c, text, params);
  await resetRole(c);
  return state;
}

describe('single-node delivery table, insert-only (stock ledger shape)', () => {
  async function setup(c: PoolClient) {
    await c.query(`create table inv.zz_ledger (
      id uuid primary key default core.uuid_v7(),
      delivery_node_id uuid not null, label text not null, qty numeric(14,3) not null)`);
    await register(c, 'inv.zz_ledger', {
      domain: 'STOCK_LEVELS',
      modifyDomain: 'STOCK_ADJUSTMENTS',
      insertOnly: true,
    });
    await c.query(
      `insert into inv.zz_ledger (delivery_node_id, label, qty) values
        ($1, 'hub', 1), ($2, 'A', 1), ($3, 'B', 1)`,
      [ids.node('delivery:Hub'), ids.node('delivery:Outlet A'), ids.node('delivery:Outlet B')],
    );
  }

  it('filters reads by node, inheritance and derived views', async () => {
    await inRolledBackTx(async (c) => {
      await setup(c);
      const see = (who: string) => visible(c, who, 'inv.zz_ledger', 'label');
      expect(await see('Olivia Outlet Manager')).toEqual(['A']);
      expect(await see('Casey Chef')).toEqual(['A']);
      expect(await see('Aria Area Manager')).toEqual(['A', 'B']); // derived via node_link
      expect(await see('Hugo Hub Manager')).toEqual(['A', 'B', 'hub']); // SUPPLY_VIEWER
      expect(await see('Outlet Ops AI Agent')).toEqual(['A', 'B', 'hub']);
      expect(await see('Sam Staff')).toEqual([]);
      expect(await see('Harper HR Admin')).toEqual([]);
    });
  });

  it('checks inserts against the modify domain and node', async () => {
    await inRolledBackTx(async (c) => {
      await setup(c);
      const ins = (who: string, node: string) =>
        tryAs(
          c,
          who,
          `insert into inv.zz_ledger (delivery_node_id, label, qty) values ($1, 'x', 1)`,
          [ids.node(`delivery:${node}`)],
        );
      expect(await ins('Casey Chef', 'Outlet A')).toBeNull();
      expect(await ins('Casey Chef', 'Outlet B')).toBe(INSUFFICIENT_PRIVILEGE);
      expect(await ins('Hugo Hub Manager', 'Hub')).toBeNull();
      expect(await ins('Hugo Hub Manager', 'Outlet A')).toBe(INSUFFICIENT_PRIVILEGE);
      expect(await ins('Aria Area Manager', 'Outlet A')).toBe(INSUFFICIENT_PRIVILEGE);
      expect(await ins('Outlet Ops AI Agent', 'Outlet A')).toBe(INSUFFICIENT_PRIVILEGE);
    });
  });

  it('never allows UPDATE or DELETE', async () => {
    await inRolledBackTx(async (c) => {
      await setup(c);
      expect(await tryAs(c, 'Casey Chef', `update inv.zz_ledger set qty = 2`)).toBe(
        INSUFFICIENT_PRIVILEGE,
      );
      expect(await tryAs(c, 'Casey Chef', `delete from inv.zz_ledger`)).toBe(
        INSUFFICIENT_PRIVILEGE,
      );
    });
  });
});

describe('two-node table (transfer shape) with wf_request_id', () => {
  async function setup(c: PoolClient) {
    await c.query(`create table inv.zz_transfer (
      id uuid primary key default core.uuid_v7(),
      from_node_id uuid not null, to_node_id uuid not null,
      label text not null, status text not null default 'draft', wf_request_id uuid)`);
    await register(c, 'inv.zz_transfer', {
      domain: 'TRANSFERS',
      nodeColumns: ['from_node_id', 'to_node_id'],
    });
    await c.query(
      `insert into inv.zz_transfer (from_node_id, to_node_id, label) values
        ($1, $2, 'hub->A'), ($1, $3, 'hub->B')`,
      [ids.node('delivery:Hub'), ids.node('delivery:Outlet A'), ids.node('delivery:Outlet B')],
    );
  }

  it('shows a row when either leg is visible', async () => {
    await inRolledBackTx(async (c) => {
      await setup(c);
      const see = (who: string) => visible(c, who, 'inv.zz_transfer', 'label');
      expect(await see('Olivia Outlet Manager')).toEqual(['hub->A']); // to-leg
      expect(await see('Kim Storekeeper')).toEqual(['hub->A']); // TRANSFERS V at A
      expect(await see('Hugo Hub Manager')).toEqual(['hub->A', 'hub->B']); // from-leg
      expect(await see('Aria Area Manager')).toEqual(['hub->A', 'hub->B']); // derived
      expect(await see('Casey Chef')).toEqual([]);
    });
  });

  it('checks modify per leg on insert', async () => {
    await inRolledBackTx(async (c) => {
      await setup(c);
      const ins = (who: string, from: string, to: string) =>
        tryAs(
          c,
          who,
          `insert into inv.zz_transfer (from_node_id, to_node_id, label) values ($1, $2, 'x')`,
          [ids.node(`delivery:${from}`), ids.node(`delivery:${to}`)],
        );
      expect(await ins('Olivia Outlet Manager', 'Hub', 'Outlet A')).toBeNull(); // receiving leg
      expect(await ins('Olivia Outlet Manager', 'Hub', 'Outlet B')).toBe(INSUFFICIENT_PRIVILEGE);
      expect(await ins('Hugo Hub Manager', 'Hub', 'Outlet B')).toBeNull(); // dispatching leg
      expect(await ins('Hugo Hub Manager', 'Outlet A', 'Outlet B')).toBe(INSUFFICIENT_PRIVILEGE);
      expect(await ins('Kim Storekeeper', 'Hub', 'Outlet A')).toBe(INSUFFICIENT_PRIVILEGE);
    });
  });

  it('allows status updates only to wf_executor', async () => {
    await inRolledBackTx(async (c) => {
      await setup(c);
      expect(
        await tryAs(c, 'Olivia Outlet Manager', `update inv.zz_transfer set status = 'approved'`),
      ).toBe(INSUFFICIENT_PRIVILEGE);
      await actAs(c, 'wf_executor', null);
      const res = await c.query(`update inv.zz_transfer set status = 'approved'`);
      expect(res.rowCount).toBe(2);
      await resetRole(c);
    });
  });
});

describe('self-service org table (leave shape)', () => {
  async function setup(c: PoolClient) {
    await c.query(`create table hr.zz_leave (
      id uuid primary key default core.uuid_v7(),
      org_node_id uuid not null, owner_user_id uuid not null, label text not null)`);
    await register(c, 'hr.zz_leave', { domain: 'LEAVE' });
    await c.query(
      `insert into hr.zz_leave (org_node_id, owner_user_id, label) values
        ($1, $2, 'sam'), ($1, $3, 'casey'), ($4, $5, 'hugo-at-B')`,
      [
        ids.node('org:Outlet A'),
        ids.user('Sam Staff'),
        ids.user('Casey Chef'),
        ids.node('org:Outlet B'),
        ids.user('Hugo Hub Manager'),
      ],
    );
  }

  it('shows own rows via SELF and team rows via hierarchy', async () => {
    await inRolledBackTx(async (c) => {
      await setup(c);
      const see = (who: string) => visible(c, who, 'hr.zz_leave', 'label');
      expect(await see('Sam Staff')).toEqual(['sam']);
      expect(await see('Casey Chef')).toEqual(['casey']);
      expect(await see('Olivia Outlet Manager')).toEqual(['casey', 'sam']);
      expect(await see('Aria Area Manager')).toEqual(['casey', 'hugo-at-B', 'sam']);
      expect(await see('Hugo Hub Manager')).toEqual(['hugo-at-B']);
    });
  });

  it('lets a worker insert only their own rows', async () => {
    await inRolledBackTx(async (c) => {
      await setup(c);
      const ins = (who: string, owner: string) =>
        tryAs(
          c,
          who,
          `insert into hr.zz_leave (org_node_id, owner_user_id, label) values ($1, $2, 'x')`,
          [ids.node('org:Outlet A'), ids.user(owner)],
        );
      expect(await ins('Sam Staff', 'Sam Staff')).toBeNull();
      expect(await ins('Sam Staff', 'Casey Chef')).toBe(INSUFFICIENT_PRIVILEGE);
      expect(await ins('Olivia Outlet Manager', 'Olivia Outlet Manager')).toBeNull();
      expect(await ins('Olivia Outlet Manager', 'Sam Staff')).toBe(INSUFFICIENT_PRIVILEGE);
      expect(await ins('Harper HR Admin', 'Sam Staff')).toBeNull();
    });
  });
});

describe('audit', () => {
  it('captures the acting user and is readable only by auditors and security admins', async () => {
    await inRolledBackTx(async (c) => {
      await c.query(`create table hr.zz_leave (
        id uuid primary key default core.uuid_v7(),
        org_node_id uuid not null, owner_user_id uuid not null, label text not null)`);
      await register(c, 'hr.zz_leave', { domain: 'LEAVE' });
      const sam = ids.user('Sam Staff');
      await actAs(c, 'app_rw', sam);
      const { rows } = await c.query<{ id: string }>(
        `insert into hr.zz_leave (org_node_id, owner_user_id, label) values ($1, $2, 'x') returning id`,
        [ids.node('org:Outlet A'), sam],
      );
      await resetRole(c);
      const rowId = rows[0]!.id;

      const log = await c.query<{ actor_id: string; op: string; label: string }>(
        `select actor_id, op, after ->> 'label' as label from audit.log
          where table_name = 'hr.zz_leave' and row_id = $1`,
        [rowId],
      );
      expect(log.rows).toEqual([{ actor_id: sam, op: 'INSERT', label: 'x' }]);

      const count = async (who: string) => {
        await actAs(c, 'app_rw', ids.user(who));
        const r = await c.query<{ n: string }>(
          `select count(*) as n from audit.log where row_id = $1`,
          [rowId],
        );
        await resetRole(c);
        return Number(r.rows[0]!.n);
      };
      expect(await count('Avery Auditor')).toBe(1);
      expect(await count('Sasha Security Admin')).toBe(1);
      expect(await count('Sam Staff')).toBe(0);
      expect(await count('Olivia Outlet Manager')).toBe(0);

      expect(await tryAs(c, 'Avery Auditor', `update audit.log set op = 'X'`)).toBe(
        INSUFFICIENT_PRIVILEGE,
      );
      expect(await tryAs(c, 'Avery Auditor', `delete from audit.log`)).toBe(INSUFFICIENT_PRIVILEGE);
      expect(
        await tryAs(
          c,
          'Avery Auditor',
          `insert into audit.log (actor_kind, table_name, op) values ('human', 'x', 'INSERT')`,
        ),
      ).toBe(INSUFFICIENT_PRIVILEGE);
      expect(await tryAs(c, 'Avery Auditor', `select * from audit.log_default`)).toBe(
        INSUFFICIENT_PRIVILEGE,
      );
    });
  });

  it('logs only changed field names for sensitive tables', async () => {
    await inRolledBackTx(async (c) => {
      await c.query(`create table hr.zz_pay (
        id uuid primary key default core.uuid_v7(),
        org_node_id uuid not null, pay_rate numeric(14,2) not null)`);
      await register(c, 'hr.zz_pay', { domain: 'COMPENSATION', audit: false });
      await c.query(`select audit.enable('hr.zz_pay'::regclass, names_only => true)`);
      const harper = ids.user('Harper HR Admin');
      await actAs(c, 'app_rw', harper);
      const { rows } = await c.query<{ id: string }>(
        `insert into hr.zz_pay (org_node_id, pay_rate) values ($1, 100) returning id`,
        [ids.node('org:Outlet A')],
      );
      await c.query(`update hr.zz_pay set pay_rate = 120 where id = $1`, [rows[0]!.id]);
      await resetRole(c);
      const log = await c.query<{
        op: string;
        before: unknown;
        after: unknown;
        changed_fields: string[];
      }>(
        `select op, before, after, changed_fields from audit.log
          where table_name = 'hr.zz_pay' order by occurred_at, op`,
      );
      expect(log.rows).toEqual([
        {
          op: 'INSERT',
          before: null,
          after: null,
          changed_fields: ['id', 'org_node_id', 'pay_rate'],
        },
        { op: 'UPDATE', before: null, after: null, changed_fields: ['pay_rate'] },
      ]);
    });
  });
});

describe('apply_domain_rls guards', () => {
  it('refuses a table that is not registered in core.domain_table', async () => {
    await inRolledBackTx(async (c) => {
      await c.query(`create table ops.zz_unregistered (id uuid primary key, org_node_id uuid)`);
      expect(
        await sqlState(c, `select core.apply_domain_rls('ops.zz_unregistered'::regclass)`),
      ).toBe('P0001');
    });
  });

  it('refuses a table missing its node column', async () => {
    await inRolledBackTx(async (c) => {
      await c.query(`create table ops.zz_no_node (id uuid primary key)`);
      await c.query(
        `insert into core.domain_table (tenant_id, table_name, domain_id)
         select t.id, 'ops.zz_no_node'::regclass, d.id from core.tenant t, core.domain d
          where d.code = 'EVENTS' limit 1`,
      );
      expect(await sqlState(c, `select core.apply_domain_rls('ops.zz_no_node'::regclass)`)).toBe(
        'P0001',
      );
    });
  });

  it('is not executable by app_rw', async () => {
    await inRolledBackTx(async (c) => {
      await actAs(c, 'app_rw', ids.user('Sasha Security Admin'));
      expect(await sqlState(c, `select core.apply_domain_rls('core.tenant'::regclass)`)).toBe(
        INSUFFICIENT_PRIVILEGE,
      );
      await resetRole(c);
    });
  });
});
