import type { PoolClient } from 'pg';
import { afterAll, beforeAll, describe, expect, it } from 'vitest';
import {
  actAs,
  closePools,
  inRolledBackTx,
  loadSeedIds,
  resetRole,
  sqlState,
  type SeedIds,
} from '../test/helpers';

// Exercises the policies generated by core.apply_domain_rls() on fixture tables.
// Every fixture lives in a migrator transaction that is rolled back.

const INSUFFICIENT_PRIVILEGE = '42501';

let ids: SeedIds;
beforeAll(async () => {
  ids = await loadSeedIds();
});
afterAll(closePools);

async function register(
  c: PoolClient,
  table: string,
  opts: {
    domain: string;
    modifyDomain?: string;
    insertOnly?: boolean;
    nodeColumns?: string[];
    audit?: boolean;
  },
): Promise<void> {
  // Registrations are tenant-independent (ADR 003): domain code + its tree.
  await c.query(
    `insert into core.domain_table
       (table_name, domain_code, modify_domain_code, hierarchy_type, insert_only, node_columns)
     select $1::regclass, $2, $4, d.hierarchy_type, $3, $5
       from core.domain d where d.code = $2
      limit 1`,
    [
      table,
      opts.domain,
      opts.insertOnly ?? false,
      opts.modifyDomain ?? null,
      opts.nodeColumns ?? null,
    ],
  );
  await c.query('select core.apply_domain_rls($1::regclass)', [table]);
  if (opts.audit ?? true) await c.query('select audit.enable($1::regclass)', [table]);
}

async function visible(c: PoolClient, who: string, table: string, col: string): Promise<string[]> {
  await actAs(c, 'app_rw', ids.user(who));
  const { rows } = await c.query<{ v: string }>(`select ${col} as v from ${table} order by 1`);
  await resetRole(c);
  return rows.map((r) => r.v);
}

async function tryAs(c: PoolClient, who: string, text: string, params: unknown[] = []) {
  await actAs(c, 'app_rw', ids.user(who));
  const state = await sqlState(c, text, params);
  await resetRole(c);
  return state;
}

describe('single-node delivery table, insert-only (stock ledger shape)', () => {
  async function setup(c: PoolClient) {
    await c.query(`create table inv.zz_ledger (
      id uuid primary key default core.uuid_v7(),
      delivery_node_id uuid not null, label text not null, qty numeric(14,3) not null)`);
    await register(c, 'inv.zz_ledger', {
      domain: 'STOCK_LEVELS',
      modifyDomain: 'STOCK_ADJUSTMENTS',
      insertOnly: true,
    });
    await c.query(
      `insert into inv.zz_ledger (delivery_node_id, label, qty) values
        ($1, 'hub', 1), ($2, 'A', 1), ($3, 'B', 1)`,
      [
        ids.node('TEST-CENTRAL-KITCHEN-STORE'),
        ids.node('TEST-BAR-3.0-KITCHEN-STORE'),
        ids.node('TEST-GUEST-HOUSE-2.0-SUPPLY'),
      ],
    );
  }

  it('filters reads by node, inheritance and derived views', async () => {
    await inRolledBackTx(async (c) => {
      await setup(c);
      const see = (who: string) => visible(c, who, 'inv.zz_ledger', 'label');
      expect(await see('test.bar-manager.3.0')).toEqual(['A']);
      expect(await see('test.cook.3.0')).toEqual(['A']);
      // derived via node_link; the central kitchen is in the area too
      expect(await see('test.area-manager')).toEqual(['A', 'B', 'hub']);
      expect(await see('test.central-kitchen-manager')).toEqual(['A', 'B', 'hub']); // SUPPLY_VIEWER
      expect(await see('ai-agent')).toEqual(['A', 'B', 'hub']);
      expect(await see('test.server.3.0')).toEqual([]);
      expect(await see('test.hr-admin')).toEqual([]);
    });
  });

  it('checks inserts against the modify domain and node', async () => {
    await inRolledBackTx(async (c) => {
      await setup(c);
      const ins = (who: string, node: string) =>
        tryAs(
          c,
          who,
          `insert into inv.zz_ledger (delivery_node_id, label, qty) values ($1, 'x', 1)`,
          [ids.node(node)],
        );
      expect(await ins('test.cook.3.0', 'TEST-BAR-3.0-KITCHEN-STORE')).toBeNull();
      expect(await ins('test.cook.3.0', 'TEST-GUEST-HOUSE-2.0-SUPPLY')).toBe(
        INSUFFICIENT_PRIVILEGE,
      );
      expect(await ins('test.central-kitchen-manager', 'TEST-CENTRAL-KITCHEN-STORE')).toBeNull();
      expect(await ins('test.central-kitchen-manager', 'TEST-BAR-3.0-KITCHEN-STORE')).toBe(
        INSUFFICIENT_PRIVILEGE,
      );
      expect(await ins('test.area-manager', 'TEST-BAR-3.0-KITCHEN-STORE')).toBe(
        INSUFFICIENT_PRIVILEGE,
      );
      expect(await ins('ai-agent', 'TEST-BAR-3.0-KITCHEN-STORE')).toBe(INSUFFICIENT_PRIVILEGE);
    });
  });

  it('never allows UPDATE or DELETE', async () => {
    await inRolledBackTx(async (c) => {
      await setup(c);
      expect(await tryAs(c, 'test.cook.3.0', `update inv.zz_ledger set qty = 2`)).toBe(
        INSUFFICIENT_PRIVILEGE,
      );
      expect(await tryAs(c, 'test.cook.3.0', `delete from inv.zz_ledger`)).toBe(
        INSUFFICIENT_PRIVILEGE,
      );
    });
  });
});

describe('two-node table (transfer shape) with wf_request_id', () => {
  async function setup(c: PoolClient) {
    await c.query(`create table inv.zz_transfer (
      id uuid primary key default core.uuid_v7(),
      from_node_id uuid not null, to_node_id uuid not null,
      label text not null, status text not null default 'draft', wf_request_id uuid)`);
    await register(c, 'inv.zz_transfer', {
      domain: 'TRANSFERS',
      nodeColumns: ['from_node_id', 'to_node_id'],
    });
    await c.query(
      `insert into inv.zz_transfer (from_node_id, to_node_id, label) values
        ($1, $2, 'hub->A'), ($1, $3, 'hub->B')`,
      [
        ids.node('TEST-CENTRAL-KITCHEN-STORE'),
        ids.node('TEST-BAR-3.0-KITCHEN-STORE'),
        ids.node('TEST-GUEST-HOUSE-2.0-SUPPLY'),
      ],
    );
  }

  it('shows a row when either leg is visible', async () => {
    await inRolledBackTx(async (c) => {
      await setup(c);
      const see = (who: string) => visible(c, who, 'inv.zz_transfer', 'label');
      expect(await see('test.bar-manager.3.0')).toEqual(['hub->A']); // to-leg
      expect(await see('test.head-cook.3.0')).toEqual(['hub->A']); // TRANSFERS V at A
      expect(await see('test.central-kitchen-manager')).toEqual(['hub->A', 'hub->B']); // from-leg
      expect(await see('test.area-manager')).toEqual(['hub->A', 'hub->B']); // derived
      // STOCK_USER at A requests transfers (ADR 009), so it sees A's leg
      expect(await see('test.cook.3.0')).toEqual(['hub->A']);
      expect(await see('test.server.3.0')).toEqual([]);
    });
  });

  it('checks modify per leg on insert', async () => {
    await inRolledBackTx(async (c) => {
      await setup(c);
      const ins = (who: string, from: string, to: string) =>
        tryAs(
          c,
          who,
          `insert into inv.zz_transfer (from_node_id, to_node_id, label) values ($1, $2, 'x')`,
          [ids.node(from), ids.node(to)],
        );
      expect(
        await ins(
          'test.bar-manager.3.0',
          'TEST-CENTRAL-KITCHEN-STORE',
          'TEST-BAR-3.0-KITCHEN-STORE',
        ),
      ).toBeNull(); // receiving leg
      expect(
        await ins(
          'test.bar-manager.3.0',
          'TEST-CENTRAL-KITCHEN-STORE',
          'TEST-GUEST-HOUSE-2.0-SUPPLY',
        ),
      ).toBe(INSUFFICIENT_PRIVILEGE);
      expect(
        await ins(
          'test.central-kitchen-manager',
          'TEST-CENTRAL-KITCHEN-STORE',
          'TEST-GUEST-HOUSE-2.0-SUPPLY',
        ),
      ).toBeNull(); // dispatching leg
      expect(
        await ins(
          'test.central-kitchen-manager',
          'TEST-BAR-3.0-KITCHEN-STORE',
          'TEST-GUEST-HOUSE-2.0-SUPPLY',
        ),
      ).toBe(INSUFFICIENT_PRIVILEGE);
      expect(
        await ins('test.head-cook.3.0', 'TEST-CENTRAL-KITCHEN-STORE', 'TEST-BAR-3.0-KITCHEN-STORE'),
      ).toBeNull(); // TRANSFERS M at A
      expect(
        await ins(
          'test.head-cook.3.0',
          'TEST-CENTRAL-KITCHEN-STORE',
          'TEST-GUEST-HOUSE-2.0-SUPPLY',
        ),
      ).toBe(INSUFFICIENT_PRIVILEGE);
    });
  });

  it('allows status updates only to wf_executor', async () => {
    await inRolledBackTx(async (c) => {
      await setup(c);
      expect(
        await tryAs(c, 'test.bar-manager.3.0', `update inv.zz_transfer set status = 'approved'`),
      ).toBe(INSUFFICIENT_PRIVILEGE);
      await actAs(c, 'wf_executor', null);
      const res = await c.query(`update inv.zz_transfer set status = 'approved'`);
      expect(res.rowCount).toBe(2);
      await resetRole(c);
    });
  });
});

describe('self-service org table (leave shape)', () => {
  async function setup(c: PoolClient) {
    await c.query(`create table hr.zz_leave (
      id uuid primary key default core.uuid_v7(),
      org_node_id uuid not null, owner_user_id uuid not null, label text not null)`);
    await register(c, 'hr.zz_leave', { domain: 'LEAVE' });
    await c.query(
      `insert into hr.zz_leave (org_node_id, owner_user_id, label) values
        ($1, $2, 'sam'), ($1, $3, 'casey'), ($4, $5, 'hugo-at-B')`,
      [
        ids.node('TEST-BAR-3.0-FLOOR-SERVICE'),
        ids.user('test.server.3.0'),
        ids.user('test.cook.3.0'),
        ids.node('TEST-GUEST-HOUSE-2.0'),
        ids.user('test.central-kitchen-manager'),
      ],
    );
  }

  it('shows own rows via SELF and team rows via hierarchy', async () => {
    await inRolledBackTx(async (c) => {
      await setup(c);
      const see = (who: string) => visible(c, who, 'hr.zz_leave', 'label');
      expect(await see('test.server.3.0')).toEqual(['sam']);
      expect(await see('test.cook.3.0')).toEqual(['casey']);
      expect(await see('test.bar-manager.3.0')).toEqual(['casey', 'sam']);
      expect(await see('test.area-manager')).toEqual(['casey', 'hugo-at-B', 'sam']);
      expect(await see('test.central-kitchen-manager')).toEqual(['hugo-at-B']);
    });
  });

  it('lets a worker insert only their own rows', async () => {
    await inRolledBackTx(async (c) => {
      await setup(c);
      const ins = (who: string, owner: string) =>
        tryAs(
          c,
          who,
          `insert into hr.zz_leave (org_node_id, owner_user_id, label) values ($1, $2, 'x')`,
          [ids.node('TEST-BAR-3.0-FLOOR-SERVICE'), ids.user(owner)],
        );
      expect(await ins('test.server.3.0', 'test.server.3.0')).toBeNull();
      expect(await ins('test.server.3.0', 'test.cook.3.0')).toBe(INSUFFICIENT_PRIVILEGE);
      expect(await ins('test.bar-manager.3.0', 'test.bar-manager.3.0')).toBeNull();
      expect(await ins('test.bar-manager.3.0', 'test.server.3.0')).toBe(INSUFFICIENT_PRIVILEGE);
      expect(await ins('test.hr-admin', 'test.server.3.0')).toBeNull();
    });
  });
});

describe('audit', () => {
  it('captures the acting user and is readable only by auditors and security admins', async () => {
    await inRolledBackTx(async (c) => {
      // like every business table, it carries tenant_id: audit rows are per customer
      await c.query(`create table hr.zz_leave (
        id uuid primary key default core.uuid_v7(), tenant_id uuid not null,
        org_node_id uuid not null, owner_user_id uuid not null, label text not null)`);
      await register(c, 'hr.zz_leave', { domain: 'LEAVE' });
      const sam = ids.user('test.server.3.0');
      await actAs(c, 'app_rw', sam);
      const { rows } = await c.query<{ id: string }>(
        `insert into hr.zz_leave (tenant_id, org_node_id, owner_user_id, label)
         values ($1, $2, $3, 'x') returning id`,
        [ids.tenant(), ids.node('TEST-BAR-3.0-FLOOR-SERVICE'), sam],
      );
      await resetRole(c);
      const rowId = rows[0]!.id;

      const log = await c.query<{ actor_id: string; op: string; label: string }>(
        `select actor_id, op, after ->> 'label' as label from audit.log
          where table_name = 'hr.zz_leave' and row_id = $1`,
        [rowId],
      );
      expect(log.rows).toEqual([{ actor_id: sam, op: 'INSERT', label: 'x' }]);

      const count = async (who: string) => {
        await actAs(c, 'app_rw', ids.user(who));
        const r = await c.query<{ n: string }>(
          `select count(*) as n from audit.log where row_id = $1`,
          [rowId],
        );
        await resetRole(c);
        return Number(r.rows[0]!.n);
      };
      expect(await count('test.auditor')).toBe(1);
      expect(await count('test.security-admin')).toBe(1);
      expect(await count('test.server.3.0')).toBe(0);
      expect(await count('test.bar-manager.3.0')).toBe(0);

      expect(await tryAs(c, 'test.auditor', `update audit.log set op = 'X'`)).toBe(
        INSUFFICIENT_PRIVILEGE,
      );
      expect(await tryAs(c, 'test.auditor', `delete from audit.log`)).toBe(INSUFFICIENT_PRIVILEGE);
      expect(
        await tryAs(
          c,
          'test.auditor',
          `insert into audit.log (actor_kind, table_name, op) values ('human', 'x', 'INSERT')`,
        ),
      ).toBe(INSUFFICIENT_PRIVILEGE);
      expect(await tryAs(c, 'test.auditor', `select * from audit.log_default`)).toBe(
        INSUFFICIENT_PRIVILEGE,
      );
    });
  });

  it('logs only changed field names for sensitive tables', async () => {
    await inRolledBackTx(async (c) => {
      await c.query(`create table hr.zz_pay (
        id uuid primary key default core.uuid_v7(),
        org_node_id uuid not null, pay_rate numeric(14,2) not null)`);
      await register(c, 'hr.zz_pay', { domain: 'COMPENSATION', audit: false });
      await c.query(`select audit.enable('hr.zz_pay'::regclass, names_only => true)`);
      const harper = ids.user('test.hr-admin');
      await actAs(c, 'app_rw', harper);
      const { rows } = await c.query<{ id: string }>(
        `insert into hr.zz_pay (org_node_id, pay_rate) values ($1, 100) returning id`,
        [ids.node('TEST-BAR-3.0-FLOOR-SERVICE')],
      );
      await c.query(`update hr.zz_pay set pay_rate = 120 where id = $1`, [rows[0]!.id]);
      await resetRole(c);
      const log = await c.query<{
        op: string;
        before: unknown;
        after: unknown;
        changed_fields: string[];
      }>(
        `select op, before, after, changed_fields from audit.log
          where table_name = 'hr.zz_pay' order by occurred_at, op`,
      );
      expect(log.rows).toEqual([
        {
          op: 'INSERT',
          before: null,
          after: null,
          changed_fields: ['id', 'org_node_id', 'pay_rate'],
        },
        { op: 'UPDATE', before: null, after: null, changed_fields: ['pay_rate'] },
      ]);
    });
  });
});

describe('apply_domain_rls guards', () => {
  it('refuses a table that is not registered in core.domain_table', async () => {
    await inRolledBackTx(async (c) => {
      await c.query(`create table ops.zz_unregistered (id uuid primary key, org_node_id uuid)`);
      expect(
        await sqlState(c, `select core.apply_domain_rls('ops.zz_unregistered'::regclass)`),
      ).toBe('P0001');
    });
  });

  it('refuses a table missing its node column', async () => {
    await inRolledBackTx(async (c) => {
      await c.query(`create table ops.zz_no_node (id uuid primary key)`);
      await c.query(
        `insert into core.domain_table (table_name, domain_code, hierarchy_type)
         values ('ops.zz_no_node'::regclass, 'EVENTS', 'org')`,
      );
      expect(await sqlState(c, `select core.apply_domain_rls('ops.zz_no_node'::regclass)`)).toBe(
        'P0001',
      );
    });
  });

  it('is not executable by app_rw', async () => {
    await inRolledBackTx(async (c) => {
      await actAs(c, 'app_rw', ids.user('test.security-admin'));
      expect(await sqlState(c, `select core.apply_domain_rls('core.tenant'::regclass)`)).toBe(
        INSUFFICIENT_PRIVILEGE,
      );
      await resetRole(c);
    });
  });
});
