// A picture of the thing itself on every item line (ADR 084), for staff who read little and
// remember pictures: garlic looks like garlic, cloves like cloves, a vodka bottle like a vodka
// bottle. Product code, like the duties and the catalogue. An item's picture comes from its
// name, in English, Hindi or Konkani, else its category; a customer's item that matches nothing
// specific is listed in the onboarding dry run so the words here can grow. Each key is shown as
// a real photo once the library has one (`PICTURE_PHOTOS`, apps/web); until then the app shows
// its line icon for the item's kind.

export type PictureGroup =
  | 'vegetable'
  | 'fruit'
  | 'herb'
  | 'spice'
  | 'grain'
  | 'dairy'
  | 'meat'
  | 'seafood'
  | 'pantry'
  | 'prep'
  | 'drink'
  | 'bar'
  | 'snack'
  | 'room'
  | 'cleaning'
  | 'packaging'
  | 'general';

export interface Picture {
  key: string;
  /** what it shows, in plain English (the picture's alt text) */
  label: string;
  group: PictureGroup;
  /** the words in an item's name that mean this picture: lower case, one to three words */
  words: readonly string[];
  /** a branded product's generic picture (Old Monk is a dark rum): shown until it has its own */
  kind?: string;
}

const p = (key: string, label: string, group: PictureGroup, words: readonly string[]): Picture => ({
  key,
  label,
  group,
  words,
});

const ITEMS: readonly Picture[] = [
  // vegetables
  p('onion', 'Onion', 'vegetable', [
    'onion',
    'onions',
    'pyaz',
    'pyaaz',
    'kanda',
    'kando',
    'shallot',
    'shallots',
  ]),
  p('spring-onion', 'Spring onion', 'vegetable', [
    'spring onion',
    'spring onions',
    'scallion',
    'scallions',
    'green onion',
    'hara pyaz',
  ]),
  p('tomato', 'Tomato', 'vegetable', [
    'tomato',
    'tomatoes',
    'tamatar',
    'cherry tomato',
    'cherry tomatoes',
  ]),
  p('potato', 'Potato', 'vegetable', ['potato', 'potatoes', 'aloo', 'alu', 'batata']),
  p('sweet-potato', 'Sweet potato', 'vegetable', [
    'sweet potato',
    'sweet potatoes',
    'shakarkandi',
    'kanga',
  ]),
  p('garlic', 'Garlic', 'vegetable', ['garlic', 'lehsun', 'lahsun', 'lasun', 'losun']),
  p('ginger', 'Ginger', 'vegetable', ['ginger', 'adrak', 'aale']),
  p('green-chilli', 'Green chilli', 'vegetable', [
    'green chilli',
    'green chillies',
    'green chili',
    'green chilies',
    'hari mirch',
    'mirchi',
    'chilli',
    'chillies',
    'chili',
    'chilies',
  ]),
  p('red-chilli', 'Fresh red chilli', 'vegetable', [
    'red chilli',
    'red chillies',
    'fresh red chilli',
    'lal mirch',
  ]),
  p('dried-red-chilli', 'Dried red chilli', 'spice', [
    'dried chilli',
    'dried chillies',
    'dry chilli',
    'dry red chilli',
    'kashmiri chilli',
    'kashmiri chillies',
    'byadgi chilli',
    'sukhi lal mirch',
    'whole red chilli',
  ]),
  p('carrot', 'Carrot', 'vegetable', ['carrot', 'carrots', 'gajar']),
  p('cucumber', 'Cucumber', 'vegetable', ['cucumber', 'cucumbers', 'kheera', 'kakdi', 'tausali']),
  p('brinjal', 'Brinjal', 'vegetable', [
    'brinjal',
    'brinjals',
    'eggplant',
    'aubergine',
    'baingan',
    'vaingim',
  ]),
  p('capsicum', 'Capsicum', 'vegetable', [
    'capsicum',
    'bell pepper',
    'bell peppers',
    'shimla mirch',
  ]),
  p('corn', 'Sweet corn', 'vegetable', [
    'corn',
    'sweet corn',
    'sweetcorn',
    'maize',
    'makai',
    'bhutta',
  ]),
  p('broccoli', 'Broccoli', 'vegetable', ['broccoli']),
  p('cauliflower', 'Cauliflower', 'vegetable', ['cauliflower', 'gobi', 'phool gobi']),
  p('cabbage', 'Cabbage', 'vegetable', ['cabbage', 'patta gobi', 'band gobi']),
  p('mushroom', 'Mushroom', 'vegetable', ['mushroom', 'mushrooms', 'button mushroom', 'khumb']),
  p('spinach', 'Spinach and leafy greens', 'vegetable', [
    'spinach',
    'palak',
    'lettuce',
    'leafy greens',
    'greens',
    'methi leaves',
    'amaranth',
    'bhaji',
    'saag',
    'rocket',
    'arugula',
  ]),
  p('peas', 'Green peas', 'vegetable', ['peas', 'green peas', 'matar', 'mutter']),
  p('green-beans', 'Green beans', 'vegetable', [
    'green beans',
    'french beans',
    'beans',
    'farasbi',
    'fansi',
  ]),
  p('okra', 'Okra', 'vegetable', ['okra', 'bhindi', 'lady finger', 'ladies finger', 'bhende']),
  p('pumpkin', 'Pumpkin', 'vegetable', [
    'pumpkin',
    'kaddu',
    'bhopla',
    'dudhi',
    'bottle gourd',
    'lauki',
  ]),
  p('beetroot', 'Beetroot', 'vegetable', ['beetroot', 'beet', 'chukandar']),
  p('radish', 'Radish', 'vegetable', ['radish', 'mooli', 'mula']),
  p('avocado', 'Avocado', 'vegetable', ['avocado', 'avocados']),
  p('olive', 'Olives', 'vegetable', ['olive', 'olives']),
  p('lemon', 'Lemon', 'fruit', ['lemon', 'lemons', 'nimbu', 'limbu']),
  p('lime', 'Lime', 'fruit', ['lime', 'limes', 'lime wedge', 'kagzi nimbu']),

  // herbs
  p('coriander-leaves', 'Coriander leaves', 'herb', [
    'coriander',
    'coriander leaves',
    'cilantro',
    'dhania',
    'hara dhania',
    'kothimbir',
    'kotmir',
  ]),
  p('mint', 'Mint leaves', 'herb', ['mint', 'mint leaves', 'pudina', 'phudino']),
  p('curry-leaves', 'Curry leaves', 'herb', [
    'curry leaves',
    'curry leaf',
    'kadi patta',
    'kadipatta',
    'karipatta',
  ]),
  p('basil', 'Basil and herbs', 'herb', [
    'basil',
    'tulsi',
    'parsley',
    'oregano',
    'thyme',
    'rosemary',
    'dill',
    'herbs',
    'mixed herbs',
  ]),
  p('lemongrass', 'Lemongrass', 'herb', ['lemongrass', 'lemon grass', 'gavati chaha']),

  // fruit
  p('pineapple', 'Pineapple', 'fruit', ['pineapple', 'pineapples', 'ananas']),
  p('mango', 'Mango', 'fruit', ['mango', 'mangoes', 'aam', 'amba', 'alphonso', 'mancurad']),
  p('banana', 'Banana', 'fruit', ['banana', 'bananas', 'kela', 'kel']),
  p('apple', 'Apple', 'fruit', ['apple', 'apples', 'seb', 'red apple']),
  p('green-apple', 'Green apple', 'fruit', ['green apple', 'green apples', 'granny smith']),
  p('grapes', 'Grapes', 'fruit', ['grape', 'grapes', 'angoor']),
  p('orange', 'Orange', 'fruit', [
    'orange',
    'oranges',
    'santra',
    'mosambi',
    'sweet lime',
    'tangerine',
  ]),
  p('watermelon', 'Watermelon', 'fruit', ['watermelon', 'tarbooz', 'kalingad']),
  p('muskmelon', 'Muskmelon', 'fruit', ['muskmelon', 'melon', 'kharbooja', 'cantaloupe']),
  p('strawberry', 'Strawberry', 'fruit', ['strawberry', 'strawberries']),
  p('cherry', 'Cherries', 'fruit', ['cherry', 'cherries', 'maraschino']),
  p('peach', 'Peach', 'fruit', ['peach', 'peaches', 'apricot']),
  p('pear', 'Pear', 'fruit', ['pear', 'pears', 'nashpati']),
  p('kiwi', 'Kiwi', 'fruit', ['kiwi', 'kiwis']),
  p('blueberry', 'Blueberries', 'fruit', ['blueberry', 'blueberries', 'berries']),
  p('pomegranate', 'Pomegranate', 'fruit', ['pomegranate', 'anaar', 'anar', 'dalimb']),
  p('papaya', 'Papaya', 'fruit', ['papaya', 'papita', 'popai']),
  p('guava', 'Guava', 'fruit', ['guava', 'amrood', 'peru']),
  p('jackfruit', 'Jackfruit', 'fruit', ['jackfruit', 'kathal', 'ponos']),
  p('coconut', 'Coconut', 'fruit', [
    'coconut',
    'coconuts',
    'fresh coconut',
    'grated coconut',
    'nariyal',
    'naal',
    'desiccated coconut',
  ]),
  p('tender-coconut', 'Tender coconut', 'fruit', [
    'tender coconut',
    'tender coconuts',
    'nariyal pani',
    'coconut water',
    'adsor',
  ]),
  p('cranberry', 'Cranberries', 'fruit', ['cranberry', 'cranberries']),
  p('hibiscus', 'Hibiscus flowers', 'herb', ['hibiscus', 'gudhal', 'roselle', 'sorrel']),
  p('rose', 'Rose petals', 'herb', ['rose', 'rose petals', 'gulab']),

  // spices
  p('cumin', 'Cumin seeds', 'spice', ['cumin', 'cumin seeds', 'jeera', 'jira', 'zeera']),
  p('clove', 'Cloves', 'spice', ['clove', 'cloves', 'laung', 'lavang', 'lovang']),
  p('cinnamon', 'Cinnamon', 'spice', [
    'cinnamon',
    'cinnamon stick',
    'cinnamon sticks',
    'dalchini',
    'cassia',
  ]),
  p('cardamom', 'Green cardamom', 'spice', [
    'cardamom',
    'green cardamom',
    'elaichi',
    'ilaichi',
    'veldode',
  ]),
  p('black-cardamom', 'Black cardamom', 'spice', [
    'black cardamom',
    'badi elaichi',
    'moti elaichi',
  ]),
  p('black-pepper', 'Black pepper', 'spice', [
    'black pepper',
    'pepper',
    'peppercorn',
    'peppercorns',
    'kali mirch',
    'miri',
  ]),
  p('turmeric', 'Turmeric', 'spice', ['turmeric', 'turmeric powder', 'haldi', 'halad']),
  p('chilli-powder', 'Red chilli powder', 'spice', [
    'chilli powder',
    'chili powder',
    'red chilli powder',
    'red chili powder',
    'kashmiri chilli powder',
    'lal mirch powder',
    'paprika',
    'cayenne',
  ]),
  p('coriander-powder', 'Coriander powder', 'spice', [
    'coriander powder',
    'dhania powder',
    'dhaniya powder',
  ]),
  p('coriander-seeds', 'Coriander seeds', 'spice', [
    'coriander seeds',
    'coriander seed',
    'sabut dhania',
    'dhane',
  ]),
  p('garam-masala', 'Garam masala', 'spice', [
    'garam masala',
    'masala powder',
    'spice mix',
    'chaat masala',
    'kitchen king',
    'sambar powder',
    'pav bhaji masala',
    'curry powder',
  ]),
  p('mustard-seeds', 'Mustard seeds', 'spice', [
    'mustard seeds',
    'mustard seed',
    'rai',
    'sarson',
    'mohri',
  ]),
  p('fennel', 'Fennel seeds', 'spice', ['fennel', 'fennel seeds', 'saunf', 'badishep']),
  p('fenugreek', 'Fenugreek seeds', 'spice', [
    'fenugreek',
    'fenugreek seeds',
    'methi seeds',
    'methi dana',
    'kasuri methi',
  ]),
  p('bay-leaf', 'Bay leaf', 'spice', ['bay leaf', 'bay leaves', 'tej patta', 'tamal patra']),
  p('star-anise', 'Star anise', 'spice', ['star anise', 'chakri phool', 'badiyan']),
  p('nutmeg', 'Nutmeg', 'spice', ['nutmeg', 'jaiphal', 'mace', 'javitri']),
  p('saffron', 'Saffron', 'spice', ['saffron', 'kesar', 'zafran']),
  p('sesame', 'Sesame seeds', 'spice', ['sesame', 'sesame seeds', 'til', 'teel']),
  p('ajwain', 'Carom seeds', 'spice', ['ajwain', 'carom', 'carom seeds', 'owa']),
  p('asafoetida', 'Asafoetida', 'spice', ['asafoetida', 'hing', 'heeng']),
  p('salt', 'Salt', 'pantry', [
    'salt',
    'namak',
    'mith',
    'sea salt',
    'rock salt',
    'black salt',
    'kala namak',
  ]),
  p('tamarind', 'Tamarind', 'pantry', ['tamarind', 'imli', 'chinch', 'tamarind pulp']),
  p('kokum', 'Kokum', 'pantry', ['kokum', 'kokam', 'bhirand', 'sola', 'amsol']),

  // grains, flours, pulses
  p('rice', 'Rice', 'grain', [
    'rice',
    'basmati',
    'basmati rice',
    'chawal',
    'tandul',
    'sona masoori',
    'jeera rice',
  ]),
  p('red-rice', 'Red rice', 'grain', [
    'red rice',
    'ukde',
    'ukda',
    'goan red rice',
    'boiled rice',
    'matta rice',
  ]),
  p('cooked-rice', 'Cooked rice', 'grain', [
    'steamed rice',
    'cooked rice',
    'steamed basmati rice',
    'plain rice',
    'bhaat',
  ]),
  p('wheat-flour', 'Wheat flour (atta)', 'grain', [
    'atta',
    'wheat flour',
    'whole wheat flour',
    'chakki atta',
    'gehun',
  ]),
  p('maida', 'White flour (maida)', 'grain', [
    'maida',
    'refined flour',
    'all purpose flour',
    'plain flour',
    'flour',
    'cake flour',
    'bread flour',
  ]),
  p('besan', 'Gram flour (besan)', 'grain', ['besan', 'gram flour', 'chickpea flour']),
  p('rice-flour', 'Rice flour', 'grain', ['rice flour', 'chawal ka atta', 'tandlache pith']),
  p('semolina', 'Semolina (rava)', 'grain', ['semolina', 'rava', 'rawa', 'sooji', 'suji']),
  p('cornflour', 'Cornflour', 'grain', ['cornflour', 'corn flour', 'cornstarch', 'corn starch']),
  p('poha', 'Flattened rice (poha)', 'grain', ['poha', 'pohe', 'flattened rice', 'beaten rice']),
  p('oats', 'Oats', 'grain', ['oats', 'oatmeal', 'muesli', 'cornflakes', 'cereal']),
  p('toor-dal', 'Toor dal', 'grain', [
    'toor dal',
    'tur dal',
    'arhar dal',
    'toovar dal',
    'pigeon pea',
    'dal',
    'daal',
    'lentils',
  ]),
  p('moong-dal', 'Moong dal', 'grain', [
    'moong dal',
    'mung dal',
    'moong',
    'green gram',
    'mung beans',
  ]),
  p('masoor-dal', 'Masoor dal', 'grain', ['masoor dal', 'masoor', 'red lentils', 'red lentil']),
  p('urad-dal', 'Urad dal', 'grain', ['urad dal', 'urad', 'black gram', 'udid']),
  p('chana', 'Chickpeas (chana)', 'grain', [
    'chana',
    'chickpeas',
    'chickpea',
    'kabuli chana',
    'chole',
    'chana dal',
    'garbanzo',
  ]),
  p('rajma', 'Kidney beans (rajma)', 'grain', [
    'rajma',
    'kidney beans',
    'red beans',
    'baked beans',
  ]),
  p('pasta', 'Pasta', 'grain', [
    'pasta',
    'penne',
    'spaghetti',
    'macaroni',
    'fusilli',
    'noodles',
    'hakka noodles',
  ]),
  p('bread', 'Bread loaf', 'grain', [
    'bread',
    'sandwich bread',
    'bread loaf',
    'loaf',
    'brown bread',
    'white bread',
    'toast',
  ]),
  p('pao', 'Pao (bread rolls)', 'grain', [
    'pao',
    'pav',
    'pau',
    'bun',
    'buns',
    'burger bun',
    'dinner roll',
    'dinner rolls',
    'ladi pav',
  ]),
  p('poi', 'Poi and flatbread', 'grain', [
    'poi',
    'pita',
    'pita bread',
    'flatbread',
    'naan',
    'roti',
    'chapati',
    'tortilla',
    'wrap',
    'wraps',
    'kulcha',
    'paratha',
  ]),
  p('baguette', 'Baguette', 'grain', ['baguette', 'french bread', 'garlic bread']),
  p('croissant', 'Croissant', 'grain', ['croissant', 'croissants', 'puff pastry', 'pastry']),
  p('cake', 'Cake', 'grain', ['cake', 'sponge cake', 'cake base', 'cupcake', 'muffin', 'muffins']),
  p('cookie', 'Biscuits and cookies', 'snack', [
    'cookie',
    'cookies',
    'biscuit',
    'biscuits',
    'rusk',
  ]),

  // dairy and eggs
  p('milk', 'Milk', 'dairy', [
    'milk',
    'doodh',
    'dudh',
    'full cream milk',
    'toned milk',
    'skimmed milk',
  ]),
  p('curd', 'Curd (dahi)', 'dairy', [
    'curd',
    'dahi',
    'yogurt',
    'yoghurt',
    'greek yogurt',
    'hung curd',
    'buttermilk',
    'chaas',
  ]),
  p('paneer', 'Paneer', 'dairy', ['paneer', 'cottage cheese', 'tofu']),
  p('cheese', 'Cheese', 'dairy', [
    'cheese',
    'cheddar',
    'cheddar cheese',
    'mozzarella',
    'parmesan',
    'processed cheese',
    'cheese slice',
    'cheese slices',
    'feta',
  ]),
  p('butter', 'Butter', 'dairy', [
    'butter',
    'makhan',
    'loni',
    'salted butter',
    'unsalted butter',
    'white butter',
  ]),
  p('ghee', 'Ghee', 'dairy', ['ghee', 'clarified butter', 'desi ghee', 'toop']),
  p('cream', 'Fresh cream', 'dairy', [
    'cream',
    'fresh cream',
    'whipping cream',
    'cooking cream',
    'malai',
    'sour cream',
  ]),
  p('condensed-milk', 'Condensed milk', 'dairy', [
    'condensed milk',
    'milkmaid',
    'khoya',
    'mawa',
    'evaporated milk',
  ]),
  p('egg', 'Eggs', 'dairy', ['egg', 'eggs', 'anda', 'ande', 'tantie']),
  p('ice-cream', 'Ice cream', 'dairy', ['ice cream', 'ice creams', 'gelato', 'kulfi', 'sorbet']),

  // meat
  p('chicken', 'Chicken', 'meat', [
    'chicken',
    'chicken curry cut',
    'chicken breast',
    'chicken thigh',
    'chicken leg',
    'chicken legs',
    'drumstick',
    'drumsticks',
    'chicken wings',
    'murgh',
    'kombi',
    'broiler',
  ]),
  p('mutton', 'Mutton', 'meat', [
    'mutton',
    'lamb',
    'goat',
    'goat meat',
    'gosht',
    'bokdo',
    'keema',
    'mince',
    'minced meat',
  ]),
  p('beef', 'Beef and buffalo', 'meat', ['beef', 'buff', 'buffalo', 'steak', 'tenderloin']),
  p('pork', 'Pork', 'meat', [
    'pork',
    'pork belly',
    'bacon',
    'ham',
    'pork chop',
    'pork ribs',
    'dukor',
    'pork loin',
  ]),
  p('sausage', 'Sausages (chouriço)', 'meat', [
    'sausage',
    'sausages',
    'chorizo',
    'chouriço',
    'chourico',
    'choris',
    'salami',
    'pepperoni',
    'hot dog',
  ]),

  // seafood
  p('fish', 'Fish', 'seafood', [
    'fish',
    'surmai',
    'kingfish',
    'king fish',
    'pomfret',
    'mackerel',
    'bangda',
    'sardine',
    'sardines',
    'tarle',
    'seer fish',
    'basa',
    'salmon',
    'tuna',
    'snapper',
    'modso',
    'chonak',
    'rawas',
    'lepo',
  ]),
  p('prawns', 'Prawns', 'seafood', [
    'prawn',
    'prawns',
    'shrimp',
    'shrimps',
    'jhinga',
    'sungta',
    'kolambi',
    'tiger prawns',
  ]),
  p('squid', 'Squid', 'seafood', ['squid', 'calamari', 'mankio', 'octopus']),
  p('crab', 'Crab', 'seafood', ['crab', 'crabs', 'kurlio', 'khekda', 'crab meat']),
  p('lobster', 'Lobster', 'seafood', ['lobster', 'lobsters']),
  p('clams', 'Clams and mussels', 'seafood', [
    'clam',
    'clams',
    'tisreo',
    'tisryo',
    'mussel',
    'mussels',
    'xinaneo',
    'shellfish',
  ]),
  p('dried-fish', 'Dried fish', 'seafood', [
    'dried fish',
    'dry fish',
    'sukat',
    'bombil',
    'bombay duck',
    'dried prawns',
    'galmo',
  ]),

  // pantry: oils, sauces, sugar, nuts
  p('oil', 'Cooking oil', 'pantry', [
    'oil',
    'cooking oil',
    'refined oil',
    'vegetable oil',
    'sunflower oil',
    'groundnut oil',
    'peanut oil',
    'rice bran oil',
    'soybean oil',
    'canola oil',
    'tel',
  ]),
  p('coconut-oil', 'Coconut oil', 'pantry', ['coconut oil', 'khobrel tel']),
  p('olive-oil', 'Olive oil', 'pantry', ['olive oil', 'extra virgin olive oil']),
  p('mustard-oil', 'Mustard oil', 'pantry', ['mustard oil', 'sarson ka tel']),
  p('sugar', 'Sugar', 'pantry', [
    'sugar',
    'cheeni',
    'shakkar',
    'sakhar',
    'castor sugar',
    'caster sugar',
    'icing sugar',
    'brown sugar',
    'demerara',
  ]),
  p('jaggery', 'Jaggery', 'pantry', [
    'jaggery',
    'gur',
    'gul',
    'palm jaggery',
    'goa jaggery',
    'madd gul',
    'coconut jaggery',
  ]),
  p('honey', 'Honey', 'pantry', ['honey', 'shahad', 'madh']),
  p('vinegar', 'Vinegar', 'pantry', [
    'vinegar',
    'toddy vinegar',
    'coconut vinegar',
    'white vinegar',
    'malt vinegar',
    'sirka',
    'apple cider vinegar',
  ]),
  p('ketchup', 'Tomato ketchup', 'pantry', [
    'ketchup',
    'tomato ketchup',
    'tomato sauce',
    'tomato puree',
    'tomato paste',
  ]),
  p('soy-sauce', 'Soy sauce', 'pantry', [
    'soy sauce',
    'soya sauce',
    'dark soy',
    'light soy',
    'oyster sauce',
    'fish sauce',
    'worcestershire',
  ]),
  p('chilli-sauce', 'Chilli sauce', 'pantry', [
    'chilli sauce',
    'chili sauce',
    'hot sauce',
    'sriracha',
    'schezwan sauce',
  ]),
  p('mayonnaise', 'Mayonnaise', 'pantry', [
    'mayonnaise',
    'mayo',
    'mustard sauce',
    'mustard',
    'dressing',
  ]),
  p('pickle', 'Pickle', 'pantry', [
    'pickle',
    'pickles',
    'achaar',
    'achar',
    'miskut',
    'jam',
    'preserve',
    'marmalade',
  ]),
  p('coconut-milk', 'Coconut milk', 'pantry', [
    'coconut milk',
    'coconut cream',
    'nariyal doodh',
    'roce',
  ]),
  p('cashew', 'Cashew nuts', 'snack', ['cashew', 'cashews', 'cashew nuts', 'kaju', 'goan cashews']),
  p('almond', 'Almonds', 'snack', ['almond', 'almonds', 'badam']),
  p('peanuts', 'Peanuts', 'snack', [
    'peanut',
    'peanuts',
    'groundnut',
    'groundnuts',
    'moongphali',
    'shengdana',
  ]),
  p('raisins', 'Raisins', 'snack', ['raisin', 'raisins', 'kishmish', 'sultanas', 'dried fruit']),
  p('dates', 'Dates', 'snack', ['date', 'dates', 'khajur', 'khajoor']),
  p('chocolate', 'Chocolate', 'snack', [
    'chocolate',
    'chocolate bar',
    'chocolates',
    'cocoa',
    'cocoa powder',
    'dark chocolate',
  ]),
  p('chips', 'Chips packet', 'snack', [
    'chips',
    'crisps',
    'potato chips',
    'banana chips',
    'wafers',
    'namkeen',
    'bhujia',
    'chakli',
    'mixture',
  ]),
  p('nachos', 'Nacho chips', 'snack', ['nachos', 'nacho', 'nacho chips', 'tortilla chips']),
  p('fries', 'French fries', 'snack', [
    'fries',
    'french fries',
    'potato wedges',
    'wedges',
    'frozen fries',
  ]),
  p('popcorn', 'Popcorn', 'snack', ['popcorn']),
  p('frozen', 'Frozen food', 'pantry', [
    'frozen',
    'frozen peas',
    'frozen corn',
    'frozen vegetables',
    'nuggets',
    'frozen snacks',
  ]),
  p('tinned', 'Tins and cans', 'pantry', [
    'tinned',
    'canned',
    'tin',
    'can of',
    'baked beans tin',
    'olives tin',
  ]),

  // prep made in the kitchen or bar
  p('masala-paste', 'Masala paste', 'prep', [
    'masala',
    'masala paste',
    'recheado',
    'recheado masala',
    'xacuti',
    'xacuti masala',
    'cafreal',
    'vindaloo',
    'marinade',
    'paste',
    'spice paste',
    'ginger garlic paste',
    'sambhar masala',
  ]),
  p('gravy', 'Gravy and curry base', 'prep', [
    'gravy',
    'curry',
    'curry base',
    'makhani',
    'makhani gravy',
    'onion tomato masala',
    'tomato gravy',
    'base gravy',
    'sauce base',
    'stock',
    'soup',
    'dal tadka',
    'sambar',
    'rassa',
    'xitt',
  ]),
  p('chutney', 'Chutney', 'prep', [
    'chutney',
    'mint chutney',
    'green chutney',
    'coconut chutney',
    'dip',
    'salsa',
    'raita',
    'thecha',
  ]),
  p('dough', 'Dough', 'prep', [
    'dough',
    'pizza dough',
    'atta dough',
    'batter',
    'idli batter',
    'dosa batter',
  ]),
  p('syrup', 'Syrup', 'prep', [
    'syrup',
    'sugar syrup',
    'simple syrup',
    'hibiscus syrup',
    'grenadine',
    'shrub',
    'cordial',
    'sour mix',
    'sweet and sour',
    'oleo',
  ]),
  p('tepache', 'Tepache (fermented pineapple)', 'prep', [
    'tepache',
    'tepache liqueur',
    'ferment',
    'fermented',
    'kombucha',
  ]),
  p('batched-cocktail', 'Batched cocktail', 'bar', [
    'pre-batched',
    'batched',
    'sangria',
    'punch',
    'negroni',
    'old fashioned',
    'manhattan',
    'house cocktail',
  ]),

  // drinks
  p('water', 'Drinking water', 'drink', [
    'water',
    'mineral water',
    'drinking water',
    'packaged water',
    'water bottle',
  ]),
  p('soda', 'Soda water', 'drink', ['soda', 'soda water', 'club soda', 'sparkling water']),
  p('tonic', 'Tonic water', 'drink', ['tonic', 'tonic water', 'indian tonic']),
  p('cola', 'Cola', 'drink', [
    'cola',
    'soft drink',
    'soft drinks',
    'lemonade',
    'ginger ale',
    'ginger beer',
  ]),
  p('orange-juice', 'Orange juice', 'drink', [
    'orange juice',
    'juice',
    'mosambi juice',
    'fruit juice',
    'pineapple juice',
    'apple juice',
    'mango juice',
  ]),
  p('cranberry-juice', 'Cranberry juice', 'drink', ['cranberry juice']),
  p('coffee', 'Coffee beans', 'drink', [
    'coffee',
    'coffee beans',
    'espresso',
    'espresso beans',
    'ground coffee',
    'instant coffee',
    'cold brew',
    'cold brew coffee',
    'filter coffee',
  ]),
  p('tea', 'Tea leaves', 'drink', [
    'tea',
    'tea leaves',
    'chai',
    'chai patti',
    'green tea',
    'tea bags',
    'black tea',
  ]),
  p('ice', 'Ice', 'drink', ['ice', 'ice cubes', 'crushed ice', 'ice block', 'barf']),
  p('beer', 'Beer bottle', 'bar', [
    'beer',
    'lager',
    'craft beer',
    'ale',
    'ipa',
    'stout',
    'pilsner',
    'wheat beer',
    'draught',
    'draft beer',
  ]),
  p('red-wine', 'Red wine', 'bar', [
    'red wine',
    'shiraz',
    'cabernet',
    'merlot',
    'pinot noir',
    'port',
    'port wine',
    'wine',
  ]),
  p('white-wine', 'White wine', 'bar', [
    'white wine',
    'chardonnay',
    'sauvignon blanc',
    'chenin blanc',
    'rose wine',
  ]),
  p('sparkling-wine', 'Sparkling wine', 'bar', [
    'sparkling wine',
    'champagne',
    'prosecco',
    'cava',
    'brut',
  ]),
  p('vodka', 'Vodka', 'bar', ['vodka']),
  p('gin', 'Gin', 'bar', ['gin', 'craft gin', 'london dry']),
  p('whisky', 'Whisky', 'bar', ['whisky', 'whiskey', 'blended whisky', 'scotch', 'blended scotch']),
  p('single-malt', 'Single malt', 'bar', ['single malt', 'malt whisky', 'malt']),
  p('bourbon', 'Bourbon', 'bar', ['bourbon', 'rye', 'rye whiskey', 'tennessee']),
  p('dark-rum', 'Dark rum', 'bar', ['dark rum', 'rum', 'spiced rum', 'gold rum']),
  p('white-rum', 'White rum', 'bar', ['white rum', 'light rum', 'silver rum']),
  p('tequila', 'Tequila', 'bar', ['tequila', 'tequila blanco', 'mezcal', 'reposado']),
  p('brandy', 'Brandy', 'bar', ['brandy', 'cognac']),
  p('feni', 'Feni', 'bar', ['feni', 'fenny', 'cashew feni', 'coconut feni', 'urrak', 'urak']),
  p('feni-nip', 'Small bottle (nip)', 'bar', ['nip', 'nips', 'miniature', 'mini bottle']),
  p('liqueur', 'Liqueur', 'bar', ['liqueur', 'liqueurs', 'amaretto', 'irish cream', 'schnapps']),
  p('coffee-liqueur', 'Coffee liqueur', 'bar', ['coffee liqueur']),
  p('triple-sec', 'Orange liqueur', 'bar', [
    'triple sec',
    'curacao',
    'blue curacao',
    'orange liqueur',
    'grand marnier',
  ]),
  p('vermouth', 'Vermouth', 'bar', ['vermouth', 'sweet vermouth', 'dry vermouth']),
  p('aperitif', 'Red bitter aperitif', 'bar', ['aperitif', 'bitter aperitif', 'aperitivo']),
  p('bitters', 'Bitters', 'bar', ['bitters', 'aromatic bitters', 'orange bitters']),
  p('sake', 'Sake', 'bar', ['sake', 'soju']),
  p('cocktail', 'Cocktail', 'bar', [
    'cocktail',
    'cocktails',
    'mocktail',
    'mocktails',
    'martini',
    'margarita',
    'mojito',
  ]),
  p('cocktail-napkins', 'Cocktail napkins', 'packaging', [
    'cocktail napkins',
    'cocktail napkin',
    'bar napkins',
    'coasters',
    'coaster',
  ]),
  p('straws', 'Straws', 'packaging', [
    'straw',
    'straws',
    'stirrer',
    'stirrers',
    'toothpicks',
    'skewers',
  ]),

  // rooms: linen and amenities
  p('bath-towel', 'Bath towel', 'room', [
    'bath towel',
    'bath towels',
    'towel',
    'towels',
    'bath sheet',
  ]),
  p('hand-towel', 'Hand towel', 'room', [
    'hand towel',
    'hand towels',
    'face towel',
    'face towels',
    'napkin cloth',
    'kitchen towel',
    'duster',
  ]),
  p('pool-towel', 'Pool towel', 'room', [
    'pool towel',
    'pool towels',
    'beach towel',
    'beach towels',
  ]),
  p('bedsheet', 'Bedsheet', 'room', [
    'bedsheet',
    'bedsheets',
    'bed sheet',
    'bed sheets',
    'sheet',
    'sheets',
    'duvet cover',
    'bed linen',
  ]),
  p('pillow', 'Pillow and cover', 'room', [
    'pillow',
    'pillows',
    'pillow cover',
    'pillow covers',
    'pillowcase',
    'pillow case',
    'cushion',
    'cushion cover',
  ]),
  p('blanket', 'Blanket and duvet', 'room', [
    'blanket',
    'blankets',
    'duvet',
    'quilt',
    'comforter',
    'razai',
  ]),
  p('bathrobe', 'Bathrobe', 'room', ['bathrobe', 'bath robe', 'robe', 'gown']),
  p('slippers', 'Slippers', 'room', ['slipper', 'slippers', 'chappal', 'flip flops']),
  p('soap', 'Soap', 'room', ['soap', 'soap bar', 'bathing soap', 'hand soap', 'soap bars']),
  p('shampoo', 'Shampoo and lotion', 'room', [
    'shampoo',
    'conditioner',
    'body wash',
    'shower gel',
    'lotion',
    'body lotion',
    'moisturiser',
    'moisturizer',
  ]),
  p('dental-kit', 'Dental kit', 'room', [
    'dental kit',
    'dental kits',
    'toothbrush',
    'toothpaste',
    'tooth brush',
  ]),
  p('shaving-kit', 'Shaving kit', 'room', ['shaving kit', 'razor', 'razors', 'shaving']),
  p('toilet-roll', 'Toilet roll', 'room', [
    'toilet roll',
    'toilet rolls',
    'toilet paper',
    'tissue roll',
    'tissue rolls',
  ]),
  p('tissues', 'Tissue box', 'room', [
    'tissue',
    'tissues',
    'tissue box',
    'facial tissue',
    'kleenex',
  ]),
  p('sanitary-bag', 'Sanitary bag', 'room', [
    'sanitary bag',
    'sanitary bags',
    'vanity kit',
    'cotton buds',
    'comb',
    'shower cap',
  ]),
  p('pool-chlorine', 'Pool chlorine', 'cleaning', [
    'chlorine',
    'pool chlorine',
    'chlorine granules',
    'chlorine tablets',
    'ph plus',
    'ph minus',
  ]),

  // cleaning
  p('floor-cleaner', 'Floor cleaner', 'cleaning', [
    'floor cleaner',
    'floor cleaning',
    'phenyl',
    'phenol',
    'surface cleaner',
    'multi surface',
    'disinfectant',
    'cleaner',
  ]),
  p('glass-cleaner', 'Glass cleaner spray', 'cleaning', [
    'glass cleaner',
    'window cleaner',
    'spray cleaner',
    'sanitiser spray',
    'sanitizer spray',
  ]),
  p('toilet-cleaner', 'Toilet cleaner', 'cleaning', ['toilet cleaner', 'bowl cleaner', 'acid']),
  p('dish-wash', 'Dishwash liquid', 'cleaning', [
    'dishwash',
    'dish wash',
    'dishwashing',
    'pril',
    'washing up liquid',
    'rinse aid',
    'dishwasher detergent',
  ]),
  p('detergent', 'Laundry detergent', 'cleaning', [
    'detergent',
    'laundry',
    'washing powder',
    'surf',
    'bleach',
    'fabric softener',
    'starch',
  ]),
  p('hand-wash', 'Hand wash', 'cleaning', [
    'hand wash',
    'handwash',
    'hand sanitiser',
    'hand sanitizer',
    'sanitiser',
    'sanitizer',
  ]),
  p('garbage-bags', 'Garbage bags', 'cleaning', [
    'garbage bag',
    'garbage bags',
    'trash bag',
    'trash bags',
    'bin bag',
    'bin bags',
    'dustbin bag',
    'dustbin bags',
    'bin liner',
    'bin liners',
  ]),
  p('sponge', 'Sponge and scrubber', 'cleaning', [
    'sponge',
    'sponges',
    'scrubber',
    'scrub pad',
    'steel wool',
  ]),
  p('gloves', 'Gloves', 'cleaning', [
    'gloves',
    'glove',
    'disposable gloves',
    'kitchen gloves',
    'rubber gloves',
  ]),
  p('broom', 'Broom and mop', 'cleaning', [
    'broom',
    'brooms',
    'jhadu',
    'mop',
    'mops',
    'mop head',
    'wiper',
  ]),
  p('bucket', 'Bucket', 'cleaning', ['bucket', 'buckets', 'balti']),

  // packaging
  p('foil', 'Aluminium foil', 'packaging', [
    'foil',
    'aluminium foil',
    'aluminum foil',
    'silver foil',
    'foil roll',
    'foil container',
    'foil containers',
  ]),
  p('cling-film', 'Cling film', 'packaging', [
    'cling film',
    'cling wrap',
    'plastic wrap',
    'food wrap',
    'stretch film',
  ]),
  p('butter-paper', 'Butter paper', 'packaging', [
    'butter paper',
    'baking paper',
    'parchment',
    'wax paper',
  ]),
  p('paper-napkins', 'Paper napkins', 'packaging', [
    'napkin',
    'napkins',
    'paper napkins',
    'paper napkin',
    'serviette',
    'serviettes',
    'tissue paper',
  ]),
  p('takeaway-box', 'Takeaway container', 'packaging', [
    'takeaway container',
    'takeaway containers',
    'takeaway box',
    'container',
    'containers',
    'food container',
    'meal box',
    'delivery box',
    'clamshell',
  ]),
  p('paper-bag', 'Paper bag', 'packaging', [
    'paper bag',
    'paper bags',
    'carry bag',
    'carry bags',
    'delivery bag',
  ]),
  p('paper-cup', 'Paper cup', 'packaging', [
    'paper cup',
    'paper cups',
    'disposable cup',
    'disposable cups',
    'cup lid',
    'cup lids',
    'glasses disposable',
  ]),
  p('cutlery-pack', 'Disposable cutlery', 'packaging', [
    'disposable cutlery',
    'spoon',
    'spoons',
    'fork',
    'forks',
    'cutlery',
    'wooden spoon',
    'plastic spoon',
  ]),
  p('box', 'Box or pack', 'general', ['box', 'pack', 'packet', 'carton', 'case', 'crate']),
  p('dish', 'A dish', 'general', ['dish', 'meal', 'thali', 'platter', 'combo']),

  // when nothing more specific matches: the category's picture
  p('vegetables', 'Vegetables', 'vegetable', [
    'vegetable',
    'vegetables',
    'veg',
    'sabzi',
    'produce',
  ]),
  p('fruits', 'Fruit', 'fruit', ['fruit', 'fruits', 'phal']),
  p('spices', 'Spices', 'spice', ['spice', 'spices', 'masale', 'whole spices']),
  p('grocery', 'Grocery sack', 'grain', [
    'grocery',
    'dry grocery',
    'staples',
    'grains',
    'pulses',
    'sack',
  ]),
  p('meat', 'Meat', 'meat', ['meat', 'non veg', 'non-veg']),
  p('seafood', 'Seafood', 'seafood', ['seafood', 'sea food']),
  p('dairy', 'Dairy', 'dairy', ['dairy', 'dairy & eggs', 'dairy and eggs']),
  p('bakery', 'Bakery', 'grain', ['bakery', 'baked goods']),
  p('spirits', 'Spirits bottle', 'bar', ['spirit', 'spirits', 'liquor', 'alcohol', 'hard liquor']),
  p('mixers', 'Mixers', 'drink', ['mixer', 'mixers', 'beverages', 'beverage', 'drinks']),
  p('bar-supplies', 'Bar supplies', 'bar', ['bar', 'bar consumables', 'bar supplies']),
  p('amenities', 'Guest amenities', 'room', [
    'amenities',
    'guest amenities',
    'amenity',
    'toiletries',
  ]),
  p('cleaning', 'Cleaning supplies', 'cleaning', [
    'cleaning',
    'housekeeping',
    'chemicals',
    'cleaning supplies',
  ]),
  p('packaging', 'Packaging', 'packaging', ['packaging', 'disposables', 'consumables']),
  p('minibar', 'Minibar', 'snack', ['minibar', 'mini bar', 'snacks', 'snack']),
  p('linen', 'Linen', 'room', ['linen', 'linens']),
];

const GROUP_OF = new Map(ITEMS.map((x) => [x.key, x.group]));
const b = (key: string, label: string, kind: string, words: readonly string[]): Picture => ({
  key,
  label,
  group: GROUP_OF.get(kind) ?? 'general',
  words,
  kind,
});

/**
 * Branded products found in Indian hotels, bars and kitchens. A brand in an item's name wins
 * over every other word ("Old Monk Dark Rum" is Old Monk), and until the library has its photo
 * it shows its kind's.
 */
const BRANDS: readonly Picture[] = [
  b('johnnie-walker-red', 'Johnnie Walker Red Label', 'whisky', [
    'johnnie walker red',
    'jw red',
    'red label whisky',
  ]),
  b('johnnie-walker-black', 'Johnnie Walker Black Label', 'whisky', [
    'johnnie walker black',
    'jw black',
    'black label',
  ]),
  b('jameson', 'Jameson Irish whiskey', 'whisky', ['jameson']),
  b('jack-daniels', "Jack Daniel's", 'bourbon', ['jack daniel', 'jack daniels', "jack daniel's"]),
  b('jim-beam', 'Jim Beam', 'bourbon', ['jim beam']),
  b('glenfiddich', 'Glenfiddich', 'single-malt', ['glenfiddich']),
  b('glenlivet', 'The Glenlivet', 'single-malt', ['glenlivet']),
  b('chivas-regal', 'Chivas Regal', 'whisky', ['chivas', 'chivas regal']),
  b('teachers', "Teacher's", 'whisky', ["teacher's", 'teachers highland']),
  b('black-dog', 'Black Dog', 'whisky', ['black dog']),
  b('blenders-pride', 'Blenders Pride', 'whisky', ['blenders pride', "blender's pride"]),
  b('royal-stag', 'Royal Stag', 'whisky', ['royal stag']),
  b('mcdowells', "McDowell's No.1", 'whisky', ['mcdowell', 'mcdowells', "mcdowell's"]),
  b('officers-choice', "Officer's Choice", 'whisky', ["officer's choice", 'officers choice']),
  b('amrut', 'Amrut', 'single-malt', ['amrut']),
  b('paul-john', 'Paul John', 'single-malt', ['paul john']),
  b('ballantines', "Ballantine's", 'whisky', ['ballantine', 'ballantines', "ballantine's"]),
  b('jw-double-black', 'Johnnie Walker Double Black', 'whisky', ['double black']),
  b('old-monk', 'Old Monk', 'dark-rum', ['old monk']),
  b('bacardi', 'Bacardi', 'white-rum', ['bacardi']),
  b('captain-morgan', 'Captain Morgan', 'dark-rum', ['captain morgan']),
  b('malibu', 'Malibu', 'liqueur', ['malibu']),
  b('havana-club', 'Havana Club', 'white-rum', ['havana club']),
  b('smirnoff', 'Smirnoff', 'vodka', ['smirnoff']),
  b('absolut', 'Absolut', 'vodka', ['absolut']),
  b('magic-moments', 'Magic Moments', 'vodka', ['magic moments']),
  b('grey-goose', 'Grey Goose', 'vodka', ['grey goose']),
  b('ketel-one', 'Ketel One', 'vodka', ['ketel one']),
  b('bombay-sapphire', 'Bombay Sapphire', 'gin', ['bombay sapphire']),
  b('beefeater', 'Beefeater', 'gin', ['beefeater']),
  b('tanqueray', 'Tanqueray', 'gin', ['tanqueray']),
  b('gordons', "Gordon's", 'gin', ["gordon's", 'gordons']),
  b('hendricks', "Hendrick's", 'gin', ["hendrick's", 'hendricks']),
  b('jose-cuervo', 'Jose Cuervo', 'tequila', ['cuervo', 'jose cuervo']),
  b('patron', 'Patrón', 'tequila', ['patron']),
  b('hennessy', 'Hennessy', 'brandy', ['hennessy']),
  b('remy-martin', 'Rémy Martin', 'brandy', ['remy martin']),
  b('honey-bee', 'Honey Bee brandy', 'brandy', ['honey bee']),
  b('mansion-house', 'Mansion House', 'brandy', ['mansion house']),
  b('kahlua', 'Kahlúa', 'coffee-liqueur', ['kahlua']),
  b('baileys', 'Baileys', 'liqueur', ['baileys', "bailey's"]),
  b('cointreau', 'Cointreau', 'triple-sec', ['cointreau']),
  b('jagermeister', 'Jägermeister', 'liqueur', ['jagermeister', 'jager']),
  b('campari', 'Campari', 'aperitif', ['campari']),
  b('aperol', 'Aperol', 'aperitif', ['aperol']),
  b('martini', 'Martini vermouth', 'vermouth', [
    'martini rosso',
    'martini bianco',
    'martini extra dry',
  ]),
  b('angostura', 'Angostura bitters', 'bitters', ['angostura']),
  b('kingfisher', 'Kingfisher', 'beer', ['kingfisher']),
  b('budweiser', 'Budweiser', 'beer', ['budweiser']),
  b('heineken', 'Heineken', 'beer', ['heineken']),
  b('corona', 'Corona', 'beer', ['corona']),
  b('tuborg', 'Tuborg', 'beer', ['tuborg']),
  b('carlsberg', 'Carlsberg', 'beer', ['carlsberg']),
  b('bira', 'Bira 91', 'beer', ['bira']),
  b('hoegaarden', 'Hoegaarden', 'beer', ['hoegaarden']),
  b('guinness', 'Guinness', 'beer', ['guinness']),
  b('stella-artois', 'Stella Artois', 'beer', ['stella artois', 'stella']),
  b('sula', 'Sula', 'red-wine', ['sula']),
  b('jacobs-creek', "Jacob's Creek", 'red-wine', ["jacob's creek", 'jacobs creek']),
  b('moet', 'Moët & Chandon', 'sparkling-wine', ['moet', 'moet chandon']),
  b('coca-cola', 'Coca-Cola', 'cola', ['coca cola', 'coke']),
  b('thums-up', 'Thums Up', 'cola', ['thums up']),
  b('pepsi', 'Pepsi', 'cola', ['pepsi']),
  b('sprite', 'Sprite', 'soda', ['sprite']),
  b('fanta', 'Fanta', 'soda', ['fanta']),
  b('seven-up', '7UP', 'soda', ['7up', '7 up', 'seven up']),
  b('limca', 'Limca', 'soda', ['limca']),
  b('mountain-dew', 'Mountain Dew', 'soda', ['mountain dew']),
  b('schweppes', 'Schweppes', 'tonic', ['schweppes']),
  b('red-bull', 'Red Bull', 'soda', ['red bull']),
  b('bisleri', 'Bisleri', 'water', ['bisleri']),
  b('kinley', 'Kinley', 'water', ['kinley']),
  b('aquafina', 'Aquafina', 'water', ['aquafina']),
  b('tropicana', 'Tropicana', 'orange-juice', ['tropicana']),
  b('amul-butter', 'Amul butter', 'butter', ['amul butter']),
  b('amul-cheese', 'Amul cheese', 'cheese', ['amul cheese']),
  b('maggi', 'Maggi', 'pasta', ['maggi']),
  b('tata-salt', 'Tata Salt', 'salt', ['tata salt']),
  b('heinz-ketchup', 'Heinz ketchup', 'ketchup', ['heinz']),
  b('kissan', 'Kissan', 'ketchup', ['kissan']),
  b('nutella', 'Nutella', 'chocolate', ['nutella']),
  b('nescafe', 'Nescafé', 'coffee', ['nescafe']),
  b('tabasco', 'Tabasco', 'chilli-sauce', ['tabasco']),
  b('hellmanns', "Hellmann's", 'mayonnaise', ["hellmann's", 'hellmanns']),
  b('kikkoman', 'Kikkoman', 'soy-sauce', ['kikkoman']),
  b('lays', "Lay's", 'chips', ["lay's", 'lays']),
  b('pringles', 'Pringles', 'chips', ['pringles']),
  b('kitkat', 'KitKat', 'chocolate', ['kitkat', 'kit kat']),
  b('cadbury-dairy-milk', 'Cadbury Dairy Milk', 'chocolate', ['dairy milk', 'cadbury']),
  b('toblerone', 'Toblerone', 'chocolate', ['toblerone']),
  b('oreo', 'Oreo', 'cookie', ['oreo']),
  b('tetley', 'Tetley', 'tea', ['tetley']),
  b('lipton', 'Lipton', 'tea', ['lipton']),
  b('twinings', 'Twinings', 'tea', ['twinings']),
  b('harpic', 'Harpic', 'toilet-cleaner', ['harpic']),
  b('lizol', 'Lizol', 'floor-cleaner', ['lizol']),
  b('colin', 'Colin', 'glass-cleaner', ['colin']),
  b('vim', 'Vim', 'dish-wash', ['vim']),
  b('dettol', 'Dettol', 'hand-wash', ['dettol']),
  b('surf-excel', 'Surf Excel', 'detergent', ['surf excel']),
  b('ariel', 'Ariel', 'detergent', ['ariel']),
  b('domex', 'Domex', 'toilet-cleaner', ['domex']),
  b('colgate', 'Colgate', 'dental-kit', ['colgate']),
  b('dove', 'Dove', 'soap', ['dove']),
  b('lux', 'Lux', 'soap', ['lux']),
  b('lifebuoy', 'Lifebuoy', 'soap', ['lifebuoy']),
  b('head-and-shoulders', 'Head & Shoulders', 'shampoo', [
    'head and shoulders',
    'head & shoulders',
  ]),
  b('scotch-brite', 'Scotch-Brite', 'sponge', ['scotch brite']),
  b('gillette', 'Gillette', 'shaving-kit', ['gillette']),
];

export const PICTURES: readonly Picture[] = [...ITEMS, ...BRANDS];

/** Pictures that only ever stand in for a category: never "specific". */
const CATEGORY_KEYS = new Set([
  'vegetables',
  'fruits',
  'spices',
  'grocery',
  'meat',
  'seafood',
  'dairy',
  'bakery',
  'spirits',
  'mixers',
  'bar-supplies',
  'amenities',
  'cleaning',
  'packaging',
  'minibar',
  'linen',
  'box',
  'dish',
]);

export const PICTURE_KEYS: readonly string[] = PICTURES.map((x) => x.key);
const BY_KEY = new Map(PICTURES.map((x) => [x.key, x]));

export function pictureOf(key: string): Picture | undefined {
  return BY_KEY.get(key);
}

/** 'Test Kashmiri Chilli, dried 750ml (Pack of 30)' -> words, sizes and "test" left out */
function tokens(s: string): string[] {
  return s
    .toLowerCase()
    .normalize('NFKD')
    .replace(/[̀-ͯ]/g, '')
    .replace(/\b\d+(\.\d+)?\s*(ml|l|ltr|cl|g|gm|gms|kg|kgs|pcs|pc|nos|no)\b/g, ' ')
    .replace(/\bpack of \d+\b/g, ' ')
    .replace(/[^a-z\s-]/g, ' ')
    .split(/[\s-]+/)
    .filter((w) => w && w !== 'test' && !/^\d+$/.test(w));
}

// every phrase, its picture and its length in words; longer phrases are tried first
const phrases = (list: readonly Picture[]) =>
  list
    .flatMap((x) => x.words.map((w) => ({ words: tokens(w), key: x.key })))
    .sort((a, b) => b.words.length - a.words.length);
const PHRASES = phrases(ITEMS);
const BRAND_PHRASES = phrases(BRANDS);

/** a word or its plural: "box" is in "Delivery boxes", "berry" in "berries" */
const same = (t: string, w: string) =>
  t === w || t === `${w}s` || t === `${w}es` || (w.endsWith('y') && t === `${w.slice(0, -1)}ies`);

/**
 * The best picture in some words: the longest phrase wins; between phrases as long, the one
 * further right (the thing itself usually comes last: "coconut curry base" is a curry base).
 */
function bestIn(
  text: string,
  list: readonly { words: readonly string[]; key: string }[] = PHRASES,
): string | null {
  const t = tokens(text);
  if (t.length === 0) return null;
  let best: { key: string; len: number; end: number } | null = null;
  for (const ph of list) {
    if (best && ph.words.length < best.len) break;
    for (let i = 0; i + ph.words.length <= t.length; i++) {
      if (ph.words.every((w, j) => same(t[i + j]!, w))) {
        const end = i + ph.words.length;
        if (!best || ph.words.length > best.len || end > best.end) {
          best = { key: ph.key, len: ph.words.length, end };
        }
      }
    }
  }
  return best?.key ?? null;
}

export interface PictureMatch {
  key: string;
  /** false when only the category (or nothing at all) gave the picture */
  specific: boolean;
}

/**
 * An item's picture from its name, then its category. A brand anywhere in the name decides
 * first ("Old Monk Dark Rum 750ml" is Old Monk). Then the name's head (before a comma or a
 * bracket), so "Chicken, curry cut" is chicken and "Refined Flour (Maida)" is maida; then what
 * is in brackets, then after the comma; then the category.
 */
export function matchPicture(name: string, category?: string | null): PictureMatch {
  const brand = bestIn(name, BRAND_PHRASES);
  if (brand) return { key: brand, specific: true };
  const head = name.split(/[,(]/)[0] ?? name;
  const bracket = /\(([^)]*)\)/.exec(name)?.[1] ?? '';
  const tail = name.includes(',') ? name.slice(name.indexOf(',') + 1) : '';
  for (const part of [head, bracket, tail]) {
    const key = bestIn(part);
    if (key && !CATEGORY_KEYS.has(key)) return { key, specific: true };
  }
  const fromCategory = category ? bestIn(category) : null;
  const fromName = bestIn(name);
  return { key: fromCategory ?? fromName ?? 'box', specific: false };
}

/** The picture's key for an item: its own when set, else matched from its name and category. */
export function pictureFor(name: string, category?: string | null): string {
  return matchPicture(name, category).key;
}
