// Written by `pnpm --filter @outlet-ops/web photos`: do not edit.
// Who took each photo in the library and under which licence (all from Wikimedia Commons).
export interface PictureCredit {
  key: string;
  label: string;
  title: string;
  author: string;
  licence: string;
  licenceUrl: string;
  source: string;
}

export const PICTURE_CREDITS: readonly PictureCredit[] = [
  {
    key: 'absolut',
    label: 'Absolut',
    title: 'A bottle of Absolut Vodka.jpg',
    author: 'Franklin Rainier',
    licence: 'Public domain',
    licenceUrl: '',
    source: 'https://commons.wikimedia.org/wiki/File:A_bottle_of_Absolut_Vodka.jpg',
  },
  {
    key: 'ajwain',
    label: 'Carom seeds',
    title: 'Ajwain.JPG',
    author: 'Miansari66',
    licence: 'Public domain',
    licenceUrl: '',
    source: 'https://commons.wikimedia.org/wiki/File:Ajwain.JPG',
  },
  {
    key: 'almond',
    label: 'Almonds',
    title: 'Liat Portal for Foodie Disorder - Raw almonds in a bowl.jpg',
    author: 'HaJunkiyada',
    licence: 'CC BY-SA 4.0',
    licenceUrl: 'https://creativecommons.org/licenses/by-sa/4.0',
    source:
      'https://commons.wikimedia.org/wiki/File:Liat_Portal_for_Foodie_Disorder_-_Raw_almonds_in_a_bowl.jpg',
  },
  {
    key: 'amrut',
    label: 'Amrut',
    title: 'Amrut singlemalt whisky 2013-06-11 18-39.jpg',
    author: 'User:Vikrambj',
    licence: 'CC BY-SA 3.0',
    licenceUrl: 'https://creativecommons.org/licenses/by-sa/3.0',
    source: 'https://commons.wikimedia.org/wiki/File:Amrut_singlemalt_whisky_2013-06-11_18-39.jpg',
  },
  {
    key: 'angostura',
    label: 'Angostura bitters',
    title: 'Angostura bottle.jpg',
    author: 'Clément Bucco-Lechat',
    licence: 'CC BY-SA 3.0',
    licenceUrl: 'https://creativecommons.org/licenses/by-sa/3.0',
    source: 'https://commons.wikimedia.org/wiki/File:Angostura_bottle.jpg',
  },
  {
    key: 'aperitif',
    label: 'Red bitter aperitif',
    title: 'Aperol 001 2025 06 08.jpg',
    author: 'Friedrich Haag',
    licence: 'CC BY-SA 4.0',
    licenceUrl: 'https://creativecommons.org/licenses/by-sa/4.0',
    source: 'https://commons.wikimedia.org/wiki/File:Aperol_001_2025_06_08.jpg',
  },
  {
    key: 'aperol',
    label: 'Aperol',
    title: 'Aperol bottle.JPG',
    author: 'LittleGun',
    licence: 'Public domain',
    licenceUrl: '',
    source: 'https://commons.wikimedia.org/wiki/File:Aperol_bottle.JPG',
  },
  {
    key: 'apple',
    label: 'Apple',
    title: 'Apple in lightbox.png',
    author: 'Apple_in_lightbox.jpg: Slewrate derivative work: Σ',
    licence: 'CC BY-SA 2.0',
    licenceUrl: 'https://creativecommons.org/licenses/by-sa/2.0',
    source: 'https://commons.wikimedia.org/wiki/File:Apple_in_lightbox.png',
  },
  {
    key: 'aquafina',
    label: 'Aquafina',
    title: 'Aquafina bottle.png',
    author: 'Hstoops',
    licence: 'CC BY 4.0',
    licenceUrl: 'https://creativecommons.org/licenses/by/4.0',
    source: 'https://commons.wikimedia.org/wiki/File:Aquafina_bottle.png',
  },
  {
    key: 'asafoetida',
    label: 'Asafoetida',
    title: 'Asafoetida.jpg',
    author: 'Wikimedia Commons',
    licence: 'CC BY-SA 3.0',
    licenceUrl: 'http://creativecommons.org/licenses/by-sa/3.0/',
    source: 'https://commons.wikimedia.org/wiki/File:Asafoetida.jpg',
  },
  {
    key: 'avocado',
    label: 'Avocado',
    title: 'Avocado red peppers.jpg',
    author: 'Nikodem Nijaki',
    licence: 'CC BY-SA 3.0',
    licenceUrl: 'https://creativecommons.org/licenses/by-sa/3.0',
    source: 'https://commons.wikimedia.org/wiki/File:Avocado_red_peppers.jpg',
  },
  {
    key: 'bacardi',
    label: 'Bacardi',
    title: 'Bacardi (on white).jpg',
    author: 'Miika Silfverberg from Vantaa, Finland',
    licence: 'CC BY-SA 2.0',
    licenceUrl: 'https://creativecommons.org/licenses/by-sa/2.0',
    source: 'https://commons.wikimedia.org/wiki/File:Bacardi_(on_white).jpg',
  },
  {
    key: 'baguette',
    label: 'Baguette',
    title: 'Baguette.jpg',
    author: 'Lionel Allorge',
    licence: 'CC BY-SA 3.0',
    licenceUrl: 'https://creativecommons.org/licenses/by-sa/3.0',
    source: 'https://commons.wikimedia.org/wiki/File:Baguette.jpg',
  },
  {
    key: 'baileys',
    label: 'Baileys',
    title: 'Baileys Original Irish Cream Bottle.jpg',
    author: 'BigBlobfish',
    licence: 'CC0',
    licenceUrl: 'http://creativecommons.org/publicdomain/zero/1.0/deed.en',
    source: 'https://commons.wikimedia.org/wiki/File:Baileys_Original_Irish_Cream_Bottle.jpg',
  },
  {
    key: 'ballantines',
    label: "Ballantine's",
    title: "Ballantine's bottle.JPG",
    author: 'Nicholas Gemini',
    licence: 'CC BY-SA 3.0',
    licenceUrl: 'https://creativecommons.org/licenses/by-sa/3.0',
    source: 'https://commons.wikimedia.org/wiki/File:Ballantine%27s_bottle.JPG',
  },
  {
    key: 'banana',
    label: 'Banana',
    title: 'NIND banana ISO1250.png',
    author: 'Trougnouf (Benoit Brummer)',
    licence: 'CC BY 4.0',
    licenceUrl: 'https://creativecommons.org/licenses/by/4.0',
    source: 'https://commons.wikimedia.org/wiki/File:NIND_banana_ISO1250.png',
  },
  {
    key: 'bar-supplies',
    label: 'Bar supplies',
    title: 'Bartools.jpg',
    author: 'Mangomix',
    licence: 'CC BY-SA 3.0',
    licenceUrl: 'https://creativecommons.org/licenses/by-sa/3.0',
    source: 'https://commons.wikimedia.org/wiki/File:Bartools.jpg',
  },
  {
    key: 'basil',
    label: 'Basil and herbs',
    title: 'Basil (Ocimum basilicum).jpg',
    author: 'Cliff Hutson',
    licence: 'CC BY 2.0',
    licenceUrl: 'https://creativecommons.org/licenses/by/2.0',
    source: 'https://commons.wikimedia.org/wiki/File:Basil_(Ocimum_basilicum).jpg',
  },
  {
    key: 'batched-cocktail',
    label: 'Batched cocktail',
    title: 'Cocktail-glass.jpg',
    author: 'Evan-Amos',
    licence: 'Public domain',
    licenceUrl: '',
    source: 'https://commons.wikimedia.org/wiki/File:Cocktail-glass.jpg',
  },
  {
    key: 'bath-towel',
    label: 'Bath towel',
    title: 'Zusammengelegte Handtücher.jpg',
    author: 'User:Mattes',
    licence: 'Public domain',
    licenceUrl: '',
    source: 'https://commons.wikimedia.org/wiki/File:Zusammengelegte_Handt%C3%BCcher.jpg',
  },
  {
    key: 'bathrobe',
    label: 'Bathrobe',
    title: 'Bademantel.JPG',
    author: 'Peng',
    licence: 'CC BY-SA 3.0',
    licenceUrl: 'http://creativecommons.org/licenses/by-sa/3.0/',
    source: 'https://commons.wikimedia.org/wiki/File:Bademantel.JPG',
  },
  {
    key: 'bay-leaf',
    label: 'Bay leaf',
    title: 'Bay Leaves.JPG',
    author: 'Miansari66',
    licence: 'Public domain',
    licenceUrl: '',
    source: 'https://commons.wikimedia.org/wiki/File:Bay_Leaves.JPG',
  },
  {
    key: 'beef',
    label: 'Beef and buffalo',
    title: 'Raw beef (cow meat).jpg',
    author: 'Aderiqueza',
    licence: 'CC BY-SA 4.0',
    licenceUrl: 'https://creativecommons.org/licenses/by-sa/4.0',
    source: 'https://commons.wikimedia.org/wiki/File:Raw_beef_(cow_meat).jpg',
  },
  {
    key: 'beer',
    label: 'Beer bottle',
    title: 'Corona Extra beer bottle (2019).png',
    author: 'Bruce The Deus',
    licence: 'CC BY-SA 4.0',
    licenceUrl: 'https://creativecommons.org/licenses/by-sa/4.0',
    source: 'https://commons.wikimedia.org/wiki/File:Corona_Extra_beer_bottle_(2019).png',
  },
  {
    key: 'beetroot',
    label: 'Beetroot',
    title: 'CDC beets.jpg',
    author: "CDC's 5 a Day",
    licence: 'Public domain',
    licenceUrl: '',
    source: 'https://commons.wikimedia.org/wiki/File:CDC_beets.jpg',
  },
  {
    key: 'besan',
    label: 'Gram flour (besan)',
    title: 'Gram flour AvL.jpg',
    author: 'AlexanderVanLoon',
    licence: 'CC BY-SA 3.0',
    licenceUrl: 'https://creativecommons.org/licenses/by-sa/3.0',
    source: 'https://commons.wikimedia.org/wiki/File:Gram_flour_AvL.jpg',
  },
  {
    key: 'bira',
    label: 'Bira 91',
    title: 'Bira 91 White beer bottle.jpg',
    author: 'Slyronit',
    licence: 'CC BY-SA 4.0',
    licenceUrl: 'https://creativecommons.org/licenses/by-sa/4.0',
    source: 'https://commons.wikimedia.org/wiki/File:Bira_91_White_beer_bottle.jpg',
  },
  {
    key: 'bisleri',
    label: 'Bisleri',
    title: 'Bisleri PET water bottles with Telugu labels.jpg',
    author: 'Veeven',
    licence: 'CC BY-SA 4.0',
    licenceUrl: 'https://creativecommons.org/licenses/by-sa/4.0',
    source:
      'https://commons.wikimedia.org/wiki/File:Bisleri_PET_water_bottles_with_Telugu_labels.jpg',
  },
  {
    key: 'bitters',
    label: 'Bitters',
    title: 'Angostura aromatic bitters dD.jpg',
    author: 'Didier Descouens',
    licence: 'CC BY-SA 3.0',
    licenceUrl: 'https://creativecommons.org/licenses/by-sa/3.0',
    source: 'https://commons.wikimedia.org/wiki/File:Angostura_aromatic_bitters_dD.jpg',
  },
  {
    key: 'black-cardamom',
    label: 'Black cardamom',
    title: 'Black cardamom pods.jpg',
    author: 'CNEcija12345',
    licence: 'CC BY-SA 4.0',
    licenceUrl: 'https://creativecommons.org/licenses/by-sa/4.0',
    source: 'https://commons.wikimedia.org/wiki/File:Black_cardamom_pods.jpg',
  },
  {
    key: 'black-dog',
    label: 'Black Dog',
    title: 'Black Dog Gold Reserve Scotch Whisky, aged 12 years.jpg',
    author: 'Amitbalani',
    licence: 'CC0',
    licenceUrl: 'http://creativecommons.org/publicdomain/zero/1.0/deed.en',
    source:
      'https://commons.wikimedia.org/wiki/File:Black_Dog_Gold_Reserve_Scotch_Whisky,_aged_12_years.jpg',
  },
  {
    key: 'black-pepper',
    label: 'Black pepper',
    title: 'Black Peppercorns.jpg',
    author: 'Xitop753',
    licence: 'CC BY-SA 4.0',
    licenceUrl: 'https://creativecommons.org/licenses/by-sa/4.0',
    source: 'https://commons.wikimedia.org/wiki/File:Black_Peppercorns.jpg',
  },
  {
    key: 'blanket',
    label: 'Blanket and duvet',
    title: 'Grey knitted blanket.jpg',
    author: 'Hannah Clover',
    licence: 'CC BY-SA 4.0',
    licenceUrl: 'https://creativecommons.org/licenses/by-sa/4.0',
    source: 'https://commons.wikimedia.org/wiki/File:Grey_knitted_blanket.jpg',
  },
  {
    key: 'blueberry',
    label: 'Blueberries',
    title: 'Blueberries in Austria.jpg',
    author: 'Tiia Monto',
    licence: 'CC BY-SA 3.0',
    licenceUrl: 'https://creativecommons.org/licenses/by-sa/3.0',
    source: 'https://commons.wikimedia.org/wiki/File:Blueberries_in_Austria.jpg',
  },
  {
    key: 'bombay-sapphire',
    label: 'Bombay Sapphire',
    title: 'Bombay sapphire bottle.jpg',
    author: 'East View Photography from Greater NYC',
    licence: 'CC BY-SA 2.0',
    licenceUrl: 'https://creativecommons.org/licenses/by-sa/2.0',
    source: 'https://commons.wikimedia.org/wiki/File:Bombay_sapphire_bottle.jpg',
  },
  {
    key: 'bourbon',
    label: 'Bourbon',
    title: 'Four Roses Bourbon.jpg',
    author: 'King4120',
    licence: 'CC BY-SA 4.0',
    licenceUrl: 'https://creativecommons.org/licenses/by-sa/4.0',
    source: 'https://commons.wikimedia.org/wiki/File:Four_Roses_Bourbon.jpg',
  },
  {
    key: 'box',
    label: 'Box or pack',
    title: 'Cardboard box.jpg',
    author: 'MrBeastRapper',
    licence: 'CC BY-SA 4.0',
    licenceUrl: 'https://creativecommons.org/licenses/by-sa/4.0',
    source: 'https://commons.wikimedia.org/wiki/File:Cardboard_box.jpg',
  },
  {
    key: 'bread',
    label: 'Bread loaf',
    title: 'Bread хлеб 01.jpg',
    author: 'Dmitry Makeev',
    licence: 'CC BY-SA 4.0',
    licenceUrl: 'https://creativecommons.org/licenses/by-sa/4.0',
    source: 'https://commons.wikimedia.org/wiki/File:Bread_%D1%85%D0%BB%D0%B5%D0%B1_01.jpg',
  },
  {
    key: 'brinjal',
    label: 'Brinjal',
    title: 'Aubergine.jpg',
    author: 'Horst Frank',
    licence: 'CC BY-SA 3.0',
    licenceUrl: 'http://creativecommons.org/licenses/by-sa/3.0/',
    source: 'https://commons.wikimedia.org/wiki/File:Aubergine.jpg',
  },
  {
    key: 'broccoli',
    label: 'Broccoli',
    title: 'Good broccoli Deal!.jpg',
    author: 'Renee Comet (Photographer)',
    licence: 'Public domain',
    licenceUrl: '',
    source: 'https://commons.wikimedia.org/wiki/File:Good_broccoli_Deal!.jpg',
  },
  {
    key: 'broom',
    label: 'Broom and mop',
    title: 'Broom, dustpan and mop - (20251231 224621).jpg',
    author: 'Nagae Iku',
    licence: 'CC0',
    licenceUrl: 'http://creativecommons.org/publicdomain/zero/1.0/deed.en',
    source:
      'https://commons.wikimedia.org/wiki/File:Broom,_dustpan_and_mop_-_(20251231_224621).jpg',
  },
  {
    key: 'bucket',
    label: 'Bucket',
    title: 'Purple plastic bucket.jpg',
    author: 'Fola01',
    licence: 'CC0',
    licenceUrl: 'http://creativecommons.org/publicdomain/zero/1.0/deed.en',
    source: 'https://commons.wikimedia.org/wiki/File:Purple_plastic_bucket.jpg',
  },
  {
    key: 'budweiser',
    label: 'Budweiser',
    title: 'Budweiser bottle.jpg',
    author: 'Nicholas Gemini',
    licence: 'CC BY-SA 3.0',
    licenceUrl: 'https://creativecommons.org/licenses/by-sa/3.0',
    source: 'https://commons.wikimedia.org/wiki/File:Budweiser_bottle.jpg',
  },
  {
    key: 'butter',
    label: 'Butter',
    title: 'NCI butter.jpg',
    author: 'Renee Comet (National Cancer Institute)',
    licence: 'Public domain',
    licenceUrl: '',
    source: 'https://commons.wikimedia.org/wiki/File:NCI_butter.jpg',
  },
  {
    key: 'cabbage',
    label: 'Cabbage',
    title: 'Couve-coração-de-boi.jpg',
    author: 'Unknown authorUnknown author',
    licence: 'CC BY 4.0',
    licenceUrl: 'https://creativecommons.org/licenses/by/4.0',
    source: 'https://commons.wikimedia.org/wiki/File:Couve-cora%C3%A7%C3%A3o-de-boi.jpg',
  },
  {
    key: 'cadbury-dairy-milk',
    label: 'Cadbury Dairy Milk',
    title: 'Cadbury Dairy Milk -Mini Bar- (3951105262).jpg',
    author: 'NINXIVI',
    licence: 'CC BY 2.0',
    licenceUrl: 'https://creativecommons.org/licenses/by/2.0',
    source:
      'https://commons.wikimedia.org/wiki/File:Cadbury_Dairy_Milk_-Mini_Bar-_(3951105262).jpg',
  },
  {
    key: 'cake',
    label: 'Cake',
    title: 'Chocolate mousse cake 2.jpg',
    author: 'Lionel Allorge',
    licence: 'CC BY-SA 3.0',
    licenceUrl: 'https://creativecommons.org/licenses/by-sa/3.0',
    source: 'https://commons.wikimedia.org/wiki/File:Chocolate_mousse_cake_2.jpg',
  },
  {
    key: 'campari',
    label: 'Campari',
    title: 'Bottle of Campari (United States).jpg',
    author: 'Kenneth C. Zirkel',
    licence: 'CC BY-SA 4.0',
    licenceUrl: 'https://creativecommons.org/licenses/by-sa/4.0',
    source: 'https://commons.wikimedia.org/wiki/File:Bottle_of_Campari_(United_States).jpg',
  },
  {
    key: 'capsicum',
    label: 'Capsicum',
    title: 'Capsicum annuum fruits IMGP0049.jpg',
    author: 'Nikodem Nijaki',
    licence: 'CC BY-SA 3.0',
    licenceUrl: 'https://creativecommons.org/licenses/by-sa/3.0',
    source: 'https://commons.wikimedia.org/wiki/File:Capsicum_annuum_fruits_IMGP0049.jpg',
  },
  {
    key: 'captain-morgan',
    label: 'Captain Morgan',
    title: 'Captain Morgan Rum - Bottle.png',
    author: 'User:Pinakpani edit by User:Bruce The Deus',
    licence: 'CC BY-SA 4.0',
    licenceUrl: 'https://creativecommons.org/licenses/by-sa/4.0',
    source: 'https://commons.wikimedia.org/wiki/File:Captain_Morgan_Rum_-_Bottle.png',
  },
  {
    key: 'cardamom',
    label: 'Green cardamom',
    title: 'Green Cardamom Pods.jpg',
    author: 'Misterneedlemouse',
    licence: 'CC0',
    licenceUrl: 'http://creativecommons.org/publicdomain/zero/1.0/deed.en',
    source: 'https://commons.wikimedia.org/wiki/File:Green_Cardamom_Pods.jpg',
  },
  {
    key: 'carlsberg',
    label: 'Carlsberg',
    title: 'Carlsberg (bottle).jpg',
    author: 'FakirNL',
    licence: 'CC BY-SA 3.0',
    licenceUrl: 'https://creativecommons.org/licenses/by-sa/3.0',
    source: 'https://commons.wikimedia.org/wiki/File:Carlsberg_(bottle).jpg',
  },
  {
    key: 'carrot',
    label: 'Carrot',
    title: 'Carrot-fb.jpg',
    author: 'Collegestudent33',
    licence: 'CC BY-SA 4.0',
    licenceUrl: 'https://creativecommons.org/licenses/by-sa/4.0',
    source: 'https://commons.wikimedia.org/wiki/File:Carrot-fb.jpg',
  },
  {
    key: 'cashew',
    label: 'Cashew nuts',
    title: 'CASHEW NUTS.jpg',
    author: 'Ranjithkumar Murugesan',
    licence: 'CC0',
    licenceUrl: 'http://creativecommons.org/publicdomain/zero/1.0/deed.en',
    source: 'https://commons.wikimedia.org/wiki/File:CASHEW_NUTS.jpg',
  },
  {
    key: 'cauliflower',
    label: 'Cauliflower',
    title: 'Cauliflower 2.jpg',
    author: 'Tiia Monto',
    licence: 'CC BY-SA 4.0',
    licenceUrl: 'https://creativecommons.org/licenses/by-sa/4.0',
    source: 'https://commons.wikimedia.org/wiki/File:Cauliflower_2.jpg',
  },
  {
    key: 'chana',
    label: 'Chickpeas (chana)',
    title: 'Chickpea 07.jpg',
    author: 'Shams948',
    licence: 'CC0',
    licenceUrl: 'http://creativecommons.org/publicdomain/zero/1.0/deed.en',
    source: 'https://commons.wikimedia.org/wiki/File:Chickpea_07.jpg',
  },
  {
    key: 'cheese',
    label: 'Cheese',
    title: 'Cheese.jpg',
    author: 'Renee Comet (Photographer)',
    licence: 'Public domain',
    licenceUrl: '',
    source: 'https://commons.wikimedia.org/wiki/File:Cheese.jpg',
  },
  {
    key: 'cherry',
    label: 'Cherries',
    title: 'Cherries black.png',
    author: 'The original uploader was Andrikkos at Greek Wikipedia.',
    licence: 'Public domain',
    licenceUrl: '',
    source: 'https://commons.wikimedia.org/wiki/File:Cherries_black.png',
  },
  {
    key: 'chicken',
    label: 'Chicken',
    title: 'Raw chicken.jpg',
    author: 'Bhaskaranaidu',
    licence: 'CC BY-SA 3.0',
    licenceUrl: 'https://creativecommons.org/licenses/by-sa/3.0',
    source: 'https://commons.wikimedia.org/wiki/File:Raw_chicken.jpg',
  },
  {
    key: 'chilli-powder',
    label: 'Red chilli powder',
    title: 'Red chilli powder.jpg',
    author: 'Maa chamunda devi enterprises pvt.ltd.',
    licence: 'CC BY-SA 4.0',
    licenceUrl: 'https://creativecommons.org/licenses/by-sa/4.0',
    source: 'https://commons.wikimedia.org/wiki/File:Red_chilli_powder.jpg',
  },
  {
    key: 'chilli-sauce',
    label: 'Chilli sauce',
    title: 'Sriraja Panich red chilli sauce.jpg',
    author: 'Paul_012',
    licence: 'Public domain',
    licenceUrl: '',
    source: 'https://commons.wikimedia.org/wiki/File:Sriraja_Panich_red_chilli_sauce.jpg',
  },
  {
    key: 'chips',
    label: 'Chips packet',
    title: 'Tayto cheese and onion crisps.jpg',
    author: 'Samuel Wiki',
    licence: 'CC0',
    licenceUrl: 'http://creativecommons.org/publicdomain/zero/1.0/deed.en',
    source: 'https://commons.wikimedia.org/wiki/File:Tayto_cheese_and_onion_crisps.jpg',
  },
  {
    key: 'chivas-regal',
    label: 'Chivas Regal',
    title: 'Chivas regal 12yo.jpg',
    author: 'Keeezawa',
    licence: 'CC BY-SA 4.0',
    licenceUrl: 'https://creativecommons.org/licenses/by-sa/4.0',
    source: 'https://commons.wikimedia.org/wiki/File:Chivas_regal_12yo.jpg',
  },
  {
    key: 'chocolate',
    label: 'Chocolate',
    title: 'Bellarom dark chocolate.jpg',
    author: 'Tiia Monto',
    licence: 'CC BY-SA 4.0',
    licenceUrl: 'https://creativecommons.org/licenses/by-sa/4.0',
    source: 'https://commons.wikimedia.org/wiki/File:Bellarom_dark_chocolate.jpg',
  },
  {
    key: 'chutney',
    label: 'Chutney',
    title: 'Green Chutney.jpg',
    author: 'Sanyabolia',
    licence: 'CC BY-SA 4.0',
    licenceUrl: 'https://creativecommons.org/licenses/by-sa/4.0',
    source: 'https://commons.wikimedia.org/wiki/File:Green_Chutney.jpg',
  },
  {
    key: 'cinnamon',
    label: 'Cinnamon',
    title: 'Cinnamon sticks (1).jpg',
    author: 'Fumikas Sagisavas',
    licence: 'CC0',
    licenceUrl: 'http://creativecommons.org/publicdomain/zero/1.0/deed.en',
    source: 'https://commons.wikimedia.org/wiki/File:Cinnamon_sticks_(1).jpg',
  },
  {
    key: 'clams',
    label: 'Clams and mussels',
    title: 'Clams muscles shellfish food.jpg',
    author: 'Jon Sullivan',
    licence: 'Public domain',
    licenceUrl: '',
    source: 'https://commons.wikimedia.org/wiki/File:Clams_muscles_shellfish_food.jpg',
  },
  {
    key: 'clove',
    label: 'Cloves',
    title: 'Cloves.JPG',
    author: 'Jorge Barrios',
    licence: 'Public domain',
    licenceUrl: '',
    source: 'https://commons.wikimedia.org/wiki/File:Cloves.JPG',
  },
  {
    key: 'coca-cola',
    label: 'Coca-Cola',
    title: 'Coca Cola glass bottle transparent.png',
    author: 'Hariadi edited by Bruce The Deus',
    licence: 'CC BY-SA 3.0',
    licenceUrl: 'https://creativecommons.org/licenses/by-sa/3.0',
    source: 'https://commons.wikimedia.org/wiki/File:Coca_Cola_glass_bottle_transparent.png',
  },
  {
    key: 'cocktail',
    label: 'Cocktail',
    title: 'Chambord French Martini Cocktail.jpg',
    author: 'Brown-Forman Corporation',
    licence: 'CC BY-SA 3.0',
    licenceUrl: 'https://creativecommons.org/licenses/by-sa/3.0',
    source: 'https://commons.wikimedia.org/wiki/File:Chambord_French_Martini_Cocktail.jpg',
  },
  {
    key: 'cocktail-napkins',
    label: 'Cocktail napkins',
    title: 'Colored cocktail napkins.jpg',
    author: 'Top Napkin',
    licence: 'CC BY-SA 4.0',
    licenceUrl: 'https://creativecommons.org/licenses/by-sa/4.0',
    source: 'https://commons.wikimedia.org/wiki/File:Colored_cocktail_napkins.jpg',
  },
  {
    key: 'coconut',
    label: 'Coconut',
    title: 'Coconut on white background.jpg',
    author: "Filo gèn'",
    licence: 'CC BY-SA 4.0',
    licenceUrl: 'https://creativecommons.org/licenses/by-sa/4.0',
    source: 'https://commons.wikimedia.org/wiki/File:Coconut_on_white_background.jpg',
  },
  {
    key: 'coconut-milk',
    label: 'Coconut milk',
    title: 'Coconut milk from can01.JPG',
    author: 'Meursault2004',
    licence: 'CC BY-SA 3.0',
    licenceUrl: 'http://creativecommons.org/licenses/by-sa/3.0/',
    source: 'https://commons.wikimedia.org/wiki/File:Coconut_milk_from_can01.JPG',
  },
  {
    key: 'coconut-oil',
    label: 'Coconut oil',
    title: 'Coconut oil 2.jpg',
    author: 'Tiia Monto',
    licence: 'CC BY-SA 4.0',
    licenceUrl: 'https://creativecommons.org/licenses/by-sa/4.0',
    source: 'https://commons.wikimedia.org/wiki/File:Coconut_oil_2.jpg',
  },
  {
    key: 'coffee',
    label: 'Coffee beans',
    title: 'Roasted coffee beans in white bowl.png',
    author: 'Alorin',
    licence: 'CC BY 4.0',
    licenceUrl: 'https://creativecommons.org/licenses/by/4.0',
    source: 'https://commons.wikimedia.org/wiki/File:Roasted_coffee_beans_in_white_bowl.png',
  },
  {
    key: 'coffee-liqueur',
    label: 'Coffee liqueur',
    title: 'Kahlúa Mexican Coffee Liquor 01.jpg',
    author: 'Indrajit Das',
    licence: 'CC BY-SA 4.0',
    licenceUrl: 'https://creativecommons.org/licenses/by-sa/4.0',
    source: 'https://commons.wikimedia.org/wiki/File:Kahl%C3%BAa_Mexican_Coffee_Liquor_01.jpg',
  },
  {
    key: 'cointreau',
    label: 'Cointreau',
    title: 'Cointreau.jpg',
    author: 'Fernando Carrizo',
    licence: 'CC BY 2.0',
    licenceUrl: 'https://creativecommons.org/licenses/by/2.0',
    source: 'https://commons.wikimedia.org/wiki/File:Cointreau.jpg',
  },
  {
    key: 'cola',
    label: 'Cola',
    title: 'Coca-cola 50cl white-bg.jpg',
    author: 'Christian Gidlöf',
    licence: 'Public domain',
    licenceUrl: '',
    source: 'https://commons.wikimedia.org/wiki/File:Coca-cola_50cl_white-bg.jpg',
  },
  {
    key: 'condensed-milk',
    label: 'Condensed milk',
    title: 'Tin of condensed milk.jpg',
    author: 'Robin from Rotterdam, Netherlands',
    licence: 'CC BY-SA 2.0',
    licenceUrl: 'https://creativecommons.org/licenses/by-sa/2.0',
    source: 'https://commons.wikimedia.org/wiki/File:Tin_of_condensed_milk.jpg',
  },
  {
    key: 'cooked-rice',
    label: 'Cooked rice',
    title: 'Cooked Rice 2.jpg',
    author: 'Gaurav Dhwaj Khadka',
    licence: 'CC BY-SA 4.0',
    licenceUrl: 'https://creativecommons.org/licenses/by-sa/4.0',
    source: 'https://commons.wikimedia.org/wiki/File:Cooked_Rice_2.jpg',
  },
  {
    key: 'cookie',
    label: 'Biscuits and cookies',
    title: 'Biscuit on white background.jpg',
    author: 'Paolo Neo',
    licence: 'Public domain',
    licenceUrl: '',
    source: 'https://commons.wikimedia.org/wiki/File:Biscuit_on_white_background.jpg',
  },
  {
    key: 'coriander-leaves',
    label: 'Coriander leaves',
    title: 'Coriander Leaves.jpg',
    author: 'Rupeshm364',
    licence: 'CC BY-SA 4.0',
    licenceUrl: 'https://creativecommons.org/licenses/by-sa/4.0',
    source: 'https://commons.wikimedia.org/wiki/File:Coriander_Leaves.jpg',
  },
  {
    key: 'coriander-powder',
    label: 'Coriander powder',
    title: 'Coriander Powder.jpg',
    author: 'Gaurav Dhwaj Khadka',
    licence: 'CC BY-SA 4.0',
    licenceUrl: 'https://creativecommons.org/licenses/by-sa/4.0',
    source: 'https://commons.wikimedia.org/wiki/File:Coriander_Powder.jpg',
  },
  {
    key: 'coriander-seeds',
    label: 'Coriander seeds',
    title: 'Coriander Seeds.jpg',
    author: 'Sanjay Acharya',
    licence: 'CC BY-SA 4.0',
    licenceUrl: 'https://creativecommons.org/licenses/by-sa/4.0',
    source: 'https://commons.wikimedia.org/wiki/File:Coriander_Seeds.jpg',
  },
  {
    key: 'corn',
    label: 'Sweet corn',
    title: 'VegCorn.jpg',
    author: 'The original Uploader was wstoakLL at English Wikipedia',
    licence: 'Public domain',
    licenceUrl: '',
    source: 'https://commons.wikimedia.org/wiki/File:VegCorn.jpg',
  },
  {
    key: 'corona',
    label: 'Corona',
    title: 'Corona Extra beer bottle (2019).png',
    author: 'Bruce The Deus',
    licence: 'CC BY-SA 4.0',
    licenceUrl: 'https://creativecommons.org/licenses/by-sa/4.0',
    source: 'https://commons.wikimedia.org/wiki/File:Corona_Extra_beer_bottle_(2019).png',
  },
  {
    key: 'crab',
    label: 'Crab',
    title: 'Blue crab of Dalyan.jpg',
    author: 'E4024',
    licence: 'CC BY-SA 4.0',
    licenceUrl: 'https://creativecommons.org/licenses/by-sa/4.0',
    source: 'https://commons.wikimedia.org/wiki/File:Blue_crab_of_Dalyan.jpg',
  },
  {
    key: 'cranberry',
    label: 'Cranberries',
    title: 'Cranberry axial section.JPG',
    author: 'Bobolo94',
    licence: 'CC BY-SA 3.0',
    licenceUrl: 'https://creativecommons.org/licenses/by-sa/3.0',
    source: 'https://commons.wikimedia.org/wiki/File:Cranberry_axial_section.JPG',
  },
  {
    key: 'cranberry-juice',
    label: 'Cranberry juice',
    title: 'Cranberry juice.jpg',
    author: 'Lisa Pinehill from Osaka, Japan',
    licence: 'CC BY-SA 2.0',
    licenceUrl: 'https://creativecommons.org/licenses/by-sa/2.0',
    source: 'https://commons.wikimedia.org/wiki/File:Cranberry_juice.jpg',
  },
  {
    key: 'cream',
    label: 'Fresh cream',
    title: 'Clotted cream (cropped).JPG',
    author: 'Biggishben',
    licence: 'CC BY-SA 3.0',
    licenceUrl: 'https://creativecommons.org/licenses/by-sa/3.0',
    source: 'https://commons.wikimedia.org/wiki/File:Clotted_cream_(cropped).JPG',
  },
  {
    key: 'croissant',
    label: 'Croissant',
    title: 'Croissant-Petr Kratochvil.jpg',
    author: 'Petr Kratochvil',
    licence: 'CC0',
    licenceUrl: 'http://creativecommons.org/publicdomain/zero/1.0/deed.en',
    source: 'https://commons.wikimedia.org/wiki/File:Croissant-Petr_Kratochvil.jpg',
  },
  {
    key: 'cucumber',
    label: 'Cucumber',
    title: 'Cucumber from Denmark.jpg',
    author: 'WiseMan42',
    licence: 'CC0',
    licenceUrl: 'http://creativecommons.org/publicdomain/zero/1.0/deed.en',
    source: 'https://commons.wikimedia.org/wiki/File:Cucumber_from_Denmark.jpg',
  },
  {
    key: 'cumin',
    label: 'Cumin seeds',
    title: 'Cumin Seeds.jpg',
    author: 'Sugeesh',
    licence: 'CC BY-SA 3.0',
    licenceUrl: 'https://creativecommons.org/licenses/by-sa/3.0',
    source: 'https://commons.wikimedia.org/wiki/File:Cumin_Seeds.jpg',
  },
  {
    key: 'curd',
    label: 'Curd (dahi)',
    title: 'Natural Yoghurt.jpg',
    author: 'Tiia Monto',
    licence: 'CC BY-SA 4.0',
    licenceUrl: 'https://creativecommons.org/licenses/by-sa/4.0',
    source: 'https://commons.wikimedia.org/wiki/File:Natural_Yoghurt.jpg',
  },
  {
    key: 'curry-leaves',
    label: 'Curry leaves',
    title: 'Murraya koenigii leaves - curry leaves.jpg',
    author: 'Sonja Pauen - Stanhopea',
    licence: 'CC BY 2.0 de',
    licenceUrl: 'https://creativecommons.org/licenses/by/2.0/de/deed.en',
    source: 'https://commons.wikimedia.org/wiki/File:Murraya_koenigii_leaves_-_curry_leaves.jpg',
  },
  {
    key: 'cutlery-pack',
    label: 'Disposable cutlery',
    title: 'Cutlery made from Cellulose Acetate Biograde.JPG',
    author: 'F. Kesselring, FKuR Willich',
    licence: 'CC BY-SA 3.0 de',
    licenceUrl: 'https://creativecommons.org/licenses/by-sa/3.0/de/deed.en',
    source:
      'https://commons.wikimedia.org/wiki/File:Cutlery_made_from_Cellulose_Acetate_Biograde.JPG',
  },
  {
    key: 'dark-rum',
    label: 'Dark rum',
    title: 'Appleton Estate Jamaica Rum 01.jpg',
    author: 'Indrajit Das',
    licence: 'CC BY-SA 4.0',
    licenceUrl: 'https://creativecommons.org/licenses/by-sa/4.0',
    source: 'https://commons.wikimedia.org/wiki/File:Appleton_Estate_Jamaica_Rum_01.jpg',
  },
  {
    key: 'dates',
    label: 'Dates',
    title: 'Dried dates.jpg',
    author: 'stu_spivack',
    licence: 'CC BY-SA 2.0',
    licenceUrl: 'https://creativecommons.org/licenses/by-sa/2.0',
    source: 'https://commons.wikimedia.org/wiki/File:Dried_dates.jpg',
  },
  {
    key: 'dental-kit',
    label: 'Dental kit',
    title: 'Toothbrush, Toothpaste, Dental Care (571741) (cropped).jpg',
    author: 'Steve Buissinne, South Africa',
    licence: 'CC0',
    licenceUrl: 'http://creativecommons.org/publicdomain/zero/1.0/deed.en',
    source:
      'https://commons.wikimedia.org/wiki/File:Toothbrush,_Toothpaste,_Dental_Care_(571741)_(cropped).jpg',
  },
  {
    key: 'dish-wash',
    label: 'Dishwash liquid',
    title: 'Dish-soap.jpg',
    author: 'user:Eladkrauz',
    licence: 'CC BY-SA 3.0',
    licenceUrl: 'https://creativecommons.org/licenses/by-sa/3.0',
    source: 'https://commons.wikimedia.org/wiki/File:Dish-soap.jpg',
  },
  {
    key: 'domex',
    label: 'Domex',
    title: 'Domestos sprey universal 750ml.jpg',
    author: 'Unilever',
    licence: 'CC BY-SA 3.0',
    licenceUrl: 'https://creativecommons.org/licenses/by-sa/3.0',
    source: 'https://commons.wikimedia.org/wiki/File:Domestos_sprey_universal_750ml.jpg',
  },
  {
    key: 'dough',
    label: 'Dough',
    title: 'Dough balls (1028134868).jpg',
    author: 'Father.Jack from Coventry, UK',
    licence: 'CC BY 2.0',
    licenceUrl: 'https://creativecommons.org/licenses/by/2.0',
    source: 'https://commons.wikimedia.org/wiki/File:Dough_balls_(1028134868).jpg',
  },
  {
    key: 'dried-fish',
    label: 'Dried fish',
    title: 'Dried fish on a string.jpg',
    author: 'TheGoodEndedHappily',
    licence: 'CC BY-SA 4.0',
    licenceUrl: 'https://creativecommons.org/licenses/by-sa/4.0',
    source: 'https://commons.wikimedia.org/wiki/File:Dried_fish_on_a_string.jpg',
  },
  {
    key: 'dried-red-chilli',
    label: 'Dried red chilli',
    title: 'Roasted dry red chilli.jpg',
    author: 'Sm faysal',
    licence: 'CC BY-SA 4.0',
    licenceUrl: 'https://creativecommons.org/licenses/by-sa/4.0',
    source: 'https://commons.wikimedia.org/wiki/File:Roasted_dry_red_chilli.jpg',
  },
  {
    key: 'egg',
    label: 'Eggs',
    title: 'Brown chicken eggs (1).jpg',
    author: 'Justus Blümer from Deutschland',
    licence: 'CC BY 2.0',
    licenceUrl: 'https://creativecommons.org/licenses/by/2.0',
    source: 'https://commons.wikimedia.org/wiki/File:Brown_chicken_eggs_(1).jpg',
  },
  {
    key: 'fanta',
    label: 'Fanta',
    title: 'Fanta Orange Glass Bottle.jpg',
    author: 'Ayakln',
    licence: 'CC BY-SA 4.0',
    licenceUrl: 'https://creativecommons.org/licenses/by-sa/4.0',
    source: 'https://commons.wikimedia.org/wiki/File:Fanta_Orange_Glass_Bottle.jpg',
  },
  {
    key: 'feni',
    label: 'Feni',
    title: 'OURO Spiced Feni and OURO Village Style Cashew Feni on the beach.jpg',
    author: 'GoanFarmer',
    licence: 'CC0',
    licenceUrl: 'http://creativecommons.org/publicdomain/zero/1.0/deed.en',
    source:
      'https://commons.wikimedia.org/wiki/File:OURO_Spiced_Feni_and_OURO_Village_Style_Cashew_Feni_on_the_beach.jpg',
  },
  {
    key: 'feni-nip',
    label: 'Small bottle (nip)',
    title: 'Alcohol miniatures.jpg',
    author: 'יאיר צפורי',
    licence: 'CC BY-SA 4.0',
    licenceUrl: 'https://creativecommons.org/licenses/by-sa/4.0',
    source: 'https://commons.wikimedia.org/wiki/File:Alcohol_miniatures.jpg',
  },
  {
    key: 'fennel',
    label: 'Fennel seeds',
    title: 'Fennel seeds.jpg',
    author: 'KENPEI',
    licence: 'CC BY-SA 3.0',
    licenceUrl: 'http://creativecommons.org/licenses/by-sa/3.0/',
    source: 'https://commons.wikimedia.org/wiki/File:Fennel_seeds.jpg',
  },
  {
    key: 'fenugreek',
    label: 'Fenugreek seeds',
    title: 'Fenugreek seeds.jpg',
    author: 'Sanjay Acharya',
    licence: 'CC BY-SA 3.0',
    licenceUrl: 'http://creativecommons.org/licenses/by-sa/3.0/',
    source: 'https://commons.wikimedia.org/wiki/File:Fenugreek_seeds.jpg',
  },
  {
    key: 'fish',
    label: 'Fish',
    title: 'South Atlantic fish on display in Hout Bay.JPG',
    author: 'Islahaddow',
    licence: 'CC BY-SA 4.0',
    licenceUrl: 'https://creativecommons.org/licenses/by-sa/4.0',
    source:
      'https://commons.wikimedia.org/wiki/File:South_Atlantic_fish_on_display_in_Hout_Bay.JPG',
  },
  {
    key: 'fries',
    label: 'French fries',
    title: 'French fries 3.jpg',
    author: 'Sri2161k',
    licence: 'CC BY-SA 4.0',
    licenceUrl: 'https://creativecommons.org/licenses/by-sa/4.0',
    source: 'https://commons.wikimedia.org/wiki/File:French_fries_3.jpg',
  },
  {
    key: 'garam-masala',
    label: 'Garam masala',
    title: 'Garam Masala.JPG',
    author: 'Miansari66',
    licence: 'Public domain',
    licenceUrl: '',
    source: 'https://commons.wikimedia.org/wiki/File:Garam_Masala.JPG',
  },
  {
    key: 'garbage-bags',
    label: 'Garbage bags',
    title: 'Black garbage bag.jpg',
    author: 'Wiki Farazi',
    licence: 'Public domain',
    licenceUrl: '',
    source: 'https://commons.wikimedia.org/wiki/File:Black_garbage_bag.jpg',
  },
  {
    key: 'garlic',
    label: 'Garlic',
    title: 'Opened garlic bulb with garlic clove.jpg',
    author: 'Dubravko Sorić SoraZG on Flickr',
    licence: 'CC BY 2.0',
    licenceUrl: 'https://creativecommons.org/licenses/by/2.0',
    source: 'https://commons.wikimedia.org/wiki/File:Opened_garlic_bulb_with_garlic_clove.jpg',
  },
  {
    key: 'ghee',
    label: 'Ghee',
    title: 'Pure Ghee-Homemade-Maharashtra.jpg',
    author: 'Phadke09',
    licence: 'CC BY-SA 4.0',
    licenceUrl: 'https://creativecommons.org/licenses/by-sa/4.0',
    source: 'https://commons.wikimedia.org/wiki/File:Pure_Ghee-Homemade-Maharashtra.jpg',
  },
  {
    key: 'gin',
    label: 'Gin',
    title: 'Aviation American Gin 01.jpg',
    author: 'Indrajit Das',
    licence: 'CC BY-SA 4.0',
    licenceUrl: 'https://creativecommons.org/licenses/by-sa/4.0',
    source: 'https://commons.wikimedia.org/wiki/File:Aviation_American_Gin_01.jpg',
  },
  {
    key: 'ginger',
    label: 'Ginger',
    title: 'Ginger 2.jpg',
    author: 'Tiia Monto',
    licence: 'CC BY-SA 4.0',
    licenceUrl: 'https://creativecommons.org/licenses/by-sa/4.0',
    source: 'https://commons.wikimedia.org/wiki/File:Ginger_2.jpg',
  },
  {
    key: 'glass-cleaner',
    label: 'Glass cleaner spray',
    title: 'Windex (48089717956).jpg',
    author: 'Ajay Suresh from New York, NY, USA',
    licence: 'CC BY 2.0',
    licenceUrl: 'https://creativecommons.org/licenses/by/2.0',
    source: 'https://commons.wikimedia.org/wiki/File:Windex_(48089717956).jpg',
  },
  {
    key: 'glenfiddich',
    label: 'Glenfiddich',
    title: 'Bottle of Glenfiddich 12yo.jpg',
    author: 'Blueye',
    licence: 'CC BY-SA 3.0',
    licenceUrl: 'https://creativecommons.org/licenses/by-sa/3.0',
    source: 'https://commons.wikimedia.org/wiki/File:Bottle_of_Glenfiddich_12yo.jpg',
  },
  {
    key: 'glenlivet',
    label: 'The Glenlivet',
    title: 'The Glenlivet 12.jpg',
    author: 'CCFoodTravel.com',
    licence: 'CC BY 2.0',
    licenceUrl: 'https://creativecommons.org/licenses/by/2.0',
    source: 'https://commons.wikimedia.org/wiki/File:The_Glenlivet_12.jpg',
  },
  {
    key: 'gordons',
    label: "Gordon's",
    title: "Gordon's Gin cropped.jpg",
    author: "Gordon's_Gin.jpg: bfishdow derivative work: Minderbinder (talk)",
    licence: 'CC BY 2.0',
    licenceUrl: 'https://creativecommons.org/licenses/by/2.0',
    source: 'https://commons.wikimedia.org/wiki/File:Gordon%27s_Gin_cropped.jpg',
  },
  {
    key: 'grapes',
    label: 'Grapes',
    title: 'Table grapes on white.jpg',
    author: 'fir0002 flagstaffotos [at] gmail.com Canon 20D + Sigma 150mm f/2.8',
    licence: 'GFDL 1.2',
    licenceUrl: 'http://www.gnu.org/licenses/old-licenses/fdl-1.2.html',
    source: 'https://commons.wikimedia.org/wiki/File:Table_grapes_on_white.jpg',
  },
  {
    key: 'gravy',
    label: 'Gravy and curry base',
    title: 'Chicken Gravy "Jhol".jpg',
    author: 'Shukanto Das',
    licence: 'CC BY-SA 4.0',
    licenceUrl: 'https://creativecommons.org/licenses/by-sa/4.0',
    source: 'https://commons.wikimedia.org/wiki/File:Chicken_Gravy_%22Jhol%22.jpg',
  },
  {
    key: 'green-apple',
    label: 'Green apple',
    title: 'Granny Smith Apples.jpg',
    author: 'Wikimedia Commons',
    licence: 'CC BY-SA 3.0',
    licenceUrl: 'http://creativecommons.org/licenses/by-sa/3.0/',
    source: 'https://commons.wikimedia.org/wiki/File:Granny_Smith_Apples.jpg',
  },
  {
    key: 'green-beans',
    label: 'Green beans',
    title: 'Beans Phaseolus vulgaris Gartenbohne.jpg',
    author: 'bluecherry.at',
    licence: 'CC BY-SA 3.0',
    licenceUrl: 'https://creativecommons.org/licenses/by-sa/3.0',
    source: 'https://commons.wikimedia.org/wiki/File:Beans_Phaseolus_vulgaris_Gartenbohne.jpg',
  },
  {
    key: 'green-chilli',
    label: 'Green chilli',
    title: 'Green chilli.jpg',
    author: 'Snarayanprince',
    licence: 'CC BY-SA 4.0',
    licenceUrl: 'https://creativecommons.org/licenses/by-sa/4.0',
    source: 'https://commons.wikimedia.org/wiki/File:Green_chilli.jpg',
  },
  {
    key: 'grey-goose',
    label: 'Grey Goose',
    title: 'Grey Goose Bottle.jpg',
    author: 'El Gran Dee',
    licence: 'CC BY 2.0',
    licenceUrl: 'https://creativecommons.org/licenses/by/2.0',
    source: 'https://commons.wikimedia.org/wiki/File:Grey_Goose_Bottle.jpg',
  },
  {
    key: 'grocery',
    label: 'Grocery sack',
    title: 'Kartoffeln im Sack freigestellt.jpg',
    author: 'Ahoek',
    licence: 'CC BY-SA 3.0',
    licenceUrl: 'https://creativecommons.org/licenses/by-sa/3.0',
    source: 'https://commons.wikimedia.org/wiki/File:Kartoffeln_im_Sack_freigestellt.jpg',
  },
  {
    key: 'guava',
    label: 'Guava',
    title: 'Guava CDC.jpg',
    author: 'Wikimedia Commons',
    licence: 'Public domain',
    licenceUrl: '',
    source: 'https://commons.wikimedia.org/wiki/File:Guava_CDC.jpg',
  },
  {
    key: 'guinness',
    label: 'Guinness',
    title: 'Guinness bottle.jpg',
    author: 'User KeyStorm on en.wikipedia',
    licence: 'CC BY-SA 2.0',
    licenceUrl: 'https://creativecommons.org/licenses/by-sa/2.0',
    source: 'https://commons.wikimedia.org/wiki/File:Guinness_bottle.jpg',
  },
  {
    key: 'hand-towel',
    label: 'Hand towel',
    title: 'Towel and small towel.jpg',
    author: 'Jessica F.',
    licence: 'CC BY 2.5',
    licenceUrl: 'https://creativecommons.org/licenses/by/2.5',
    source: 'https://commons.wikimedia.org/wiki/File:Towel_and_small_towel.jpg',
  },
  {
    key: 'hand-wash',
    label: 'Hand wash',
    title: 'Reeva antibacterial liquid soap.jpg',
    author: 'Ajpolino',
    licence: 'CC BY-SA 4.0',
    licenceUrl: 'https://creativecommons.org/licenses/by-sa/4.0',
    source: 'https://commons.wikimedia.org/wiki/File:Reeva_antibacterial_liquid_soap.jpg',
  },
  {
    key: 'havana-club',
    label: 'Havana Club',
    title: 'Havana Club Anejo Oro.png',
    author: 'Knut.C',
    licence: 'Public domain',
    licenceUrl: '',
    source: 'https://commons.wikimedia.org/wiki/File:Havana_Club_Anejo_Oro.png',
  },
  {
    key: 'head-and-shoulders',
    label: 'Head & Shoulders',
    title: 'Head & Shoulders shampoo bottle.jpg',
    author: 'רנדום',
    licence: 'CC BY-SA 3.0',
    licenceUrl: 'https://creativecommons.org/licenses/by-sa/3.0',
    source: 'https://commons.wikimedia.org/wiki/File:Head_%26_Shoulders_shampoo_bottle.jpg',
  },
  {
    key: 'heineken',
    label: 'Heineken',
    title: 'Heineken Bottle.jpg',
    author: 'Uttamstef12',
    licence: 'CC BY-SA 3.0',
    licenceUrl: 'https://creativecommons.org/licenses/by-sa/3.0',
    source: 'https://commons.wikimedia.org/wiki/File:Heineken_Bottle.jpg',
  },
  {
    key: 'heinz-ketchup',
    label: 'Heinz ketchup',
    title: 'Heinz Tomato Ketchup, Canada (front), 2026-02-19.jpg',
    author: 'Chris Woodrich',
    licence: 'Public domain',
    licenceUrl: '',
    source:
      'https://commons.wikimedia.org/wiki/File:Heinz_Tomato_Ketchup,_Canada_(front),_2026-02-19.jpg',
  },
  {
    key: 'hendricks',
    label: "Hendrick's",
    title: "Hendrick's Gin - Bottle.png",
    author: 'User:Mikaf1fan edit by User:Bruce The Deus',
    licence: 'CC BY-SA 4.0',
    licenceUrl: 'https://creativecommons.org/licenses/by-sa/4.0',
    source: 'https://commons.wikimedia.org/wiki/File:Hendrick%27s_Gin_-_Bottle.png',
  },
  {
    key: 'hennessy',
    label: 'Hennessy',
    title: 'Cognac Hennessy Very Special.jpg',
    author: 'AlMare',
    licence: 'CC BY-SA 3.0',
    licenceUrl: 'https://creativecommons.org/licenses/by-sa/3.0',
    source: 'https://commons.wikimedia.org/wiki/File:Cognac_Hennessy_Very_Special.jpg',
  },
  {
    key: 'hibiscus',
    label: 'Hibiscus flowers',
    title: 'Dried Hibiscus flowers.jpg',
    author: 'Emily Allen from Minneapolis, USA',
    licence: 'CC BY 2.0',
    licenceUrl: 'https://creativecommons.org/licenses/by/2.0',
    source: 'https://commons.wikimedia.org/wiki/File:Dried_Hibiscus_flowers.jpg',
  },
  {
    key: 'hoegaarden',
    label: 'Hoegaarden',
    title: 'Hoegaarden bottle.JPG',
    author: 'Soti',
    licence: 'CC BY-SA 3.0',
    licenceUrl: 'https://creativecommons.org/licenses/by-sa/3.0',
    source: 'https://commons.wikimedia.org/wiki/File:Hoegaarden_bottle.JPG',
  },
  {
    key: 'honey',
    label: 'Honey',
    title: 'Dipper stick and honey in a jar.jpg',
    author: 'Shixart1985',
    licence: 'CC BY 2.0',
    licenceUrl: 'https://creativecommons.org/licenses/by/2.0',
    source: 'https://commons.wikimedia.org/wiki/File:Dipper_stick_and_honey_in_a_jar.jpg',
  },
  {
    key: 'ice',
    label: 'Ice',
    title: 'Ice-Cubes.jpg',
    author: 'בר',
    licence: 'CC BY-SA 3.0',
    licenceUrl: 'https://creativecommons.org/licenses/by-sa/3.0',
    source: 'https://commons.wikimedia.org/wiki/File:Ice-Cubes.jpg',
  },
  {
    key: 'ice-cream',
    label: 'Ice cream',
    title: 'Strawberry ice cream 2.jpg',
    author: 'Tiia Monto',
    licence: 'CC BY-SA 4.0',
    licenceUrl: 'https://creativecommons.org/licenses/by-sa/4.0',
    source: 'https://commons.wikimedia.org/wiki/File:Strawberry_ice_cream_2.jpg',
  },
  {
    key: 'jack-daniels',
    label: "Jack Daniel's",
    title: "Jack Daniel's whiskey (butelka).JPG",
    author: 'Mateusz Opasiński',
    licence: 'CC BY-SA 3.0',
    licenceUrl: 'https://creativecommons.org/licenses/by-sa/3.0',
    source: 'https://commons.wikimedia.org/wiki/File:Jack_Daniel%27s_whiskey_(butelka).JPG',
  },
  {
    key: 'jackfruit',
    label: 'Jackfruit',
    title: 'Jackfruit Pulp.jpg',
    author: 'Gharouni',
    licence: 'CC BY-SA 4.0',
    licenceUrl: 'https://creativecommons.org/licenses/by-sa/4.0',
    source: 'https://commons.wikimedia.org/wiki/File:Jackfruit_Pulp.jpg',
  },
  {
    key: 'jacobs-creek',
    label: "Jacob's Creek",
    title: "Jacob's Creek Chardonnay Pinot Noir.png",
    author: 'Catherine from Australia',
    licence: 'CC BY 4.0',
    licenceUrl: 'https://creativecommons.org/licenses/by/4.0',
    source: 'https://commons.wikimedia.org/wiki/File:Jacob%27s_Creek_Chardonnay_Pinot_Noir.png',
  },
  {
    key: 'jagermeister',
    label: 'Jägermeister',
    title: 'Jagermeister bottle.jpg',
    author: 'Pieter1',
    licence: 'Public domain',
    licenceUrl: '',
    source: 'https://commons.wikimedia.org/wiki/File:Jagermeister_bottle.jpg',
  },
  {
    key: 'jaggery',
    label: 'Jaggery',
    title: 'Sa-indian-gud.jpg',
    author: 'Sanjay ach',
    licence: 'CC BY-SA 3.0',
    licenceUrl: 'http://creativecommons.org/licenses/by-sa/3.0/',
    source: 'https://commons.wikimedia.org/wiki/File:Sa-indian-gud.jpg',
  },
  {
    key: 'jameson',
    label: 'Jameson Irish whiskey',
    title: 'Jameson Irish Whiskey.JPG',
    author: 'Datenralfi',
    licence: 'CC BY-SA 3.0 de',
    licenceUrl: 'https://creativecommons.org/licenses/by-sa/3.0/de/deed.en',
    source: 'https://commons.wikimedia.org/wiki/File:Jameson_Irish_Whiskey.JPG',
  },
  {
    key: 'jim-beam',
    label: 'Jim Beam',
    title: 'Jim Beam White Label.jpg',
    author: 'Felix Stember',
    licence: 'CC BY-SA 3.0',
    licenceUrl: 'https://creativecommons.org/licenses/by-sa/3.0',
    source: 'https://commons.wikimedia.org/wiki/File:Jim_Beam_White_Label.jpg',
  },
  {
    key: 'johnnie-walker-black',
    label: 'Johnnie Walker Black Label',
    title: 'Johnnie Walker Black Label.jpg',
    author: 'Iceman7840',
    licence: 'CC BY-SA 3.0',
    licenceUrl: 'https://creativecommons.org/licenses/by-sa/3.0',
    source: 'https://commons.wikimedia.org/wiki/File:Johnnie_Walker_Black_Label.jpg',
  },
  {
    key: 'johnnie-walker-red',
    label: 'Johnnie Walker Red Label',
    title: 'Johnnie Walker Red Label Blended Scotch Whisky 01.jpg',
    author: 'Indrajit Das',
    licence: 'CC BY-SA 4.0',
    licenceUrl: 'https://creativecommons.org/licenses/by-sa/4.0',
    source:
      'https://commons.wikimedia.org/wiki/File:Johnnie_Walker_Red_Label_Blended_Scotch_Whisky_01.jpg',
  },
  {
    key: 'jw-double-black',
    label: 'Johnnie Walker Double Black',
    title: 'JW Double Black.jpg',
    author: 'Iceman7840',
    licence: 'CC BY-SA 3.0',
    licenceUrl: 'https://creativecommons.org/licenses/by-sa/3.0',
    source: 'https://commons.wikimedia.org/wiki/File:JW_Double_Black.jpg',
  },
  {
    key: 'kahlua',
    label: 'Kahlúa',
    title: 'Kahlúa 700ml imported glass bottle - transparent (2016).png',
    author: 'Own work edit from Ikokujin',
    licence: 'CC BY-SA 4.0',
    licenceUrl: 'https://creativecommons.org/licenses/by-sa/4.0',
    source:
      'https://commons.wikimedia.org/wiki/File:Kahl%C3%BAa_700ml_imported_glass_bottle_-_transparent_(2016).png',
  },
  {
    key: 'ketchup',
    label: 'Tomato ketchup',
    title: 'Heinz Tomato Ketchup, Canada (front), 2026-02-19.jpg',
    author: 'Chris Woodrich',
    licence: 'Public domain',
    licenceUrl: '',
    source:
      'https://commons.wikimedia.org/wiki/File:Heinz_Tomato_Ketchup,_Canada_(front),_2026-02-19.jpg',
  },
  {
    key: 'kingfisher',
    label: 'Kingfisher',
    title: 'Kingfisher Premium Lager Beer.jpg',
    author: 'FakirNL',
    licence: 'CC BY-SA 4.0',
    licenceUrl: 'https://creativecommons.org/licenses/by-sa/4.0',
    source: 'https://commons.wikimedia.org/wiki/File:Kingfisher_Premium_Lager_Beer.jpg',
  },
  {
    key: 'kitkat',
    label: 'KitKat',
    title: 'Kit Kat Delight Dark (India, 2025) 01.jpg',
    author: 'Gpkp',
    licence: 'CC BY-SA 4.0',
    licenceUrl: 'https://creativecommons.org/licenses/by-sa/4.0',
    source: 'https://commons.wikimedia.org/wiki/File:Kit_Kat_Delight_Dark_(India,_2025)_01.jpg',
  },
  {
    key: 'kiwi',
    label: 'Kiwi',
    title: 'Kiwi (Actinidia chinensis) 1 Luc Viatour edit.jpg',
    author: 'Luc Viatour',
    licence: 'CC BY-SA 2.5',
    licenceUrl: 'https://creativecommons.org/licenses/by-sa/2.5',
    source:
      'https://commons.wikimedia.org/wiki/File:Kiwi_(Actinidia_chinensis)_1_Luc_Viatour_edit.jpg',
  },
  {
    key: 'kokum',
    label: 'Kokum',
    title: 'Garcinia indica - fruits, seeds, pulp and rinds.jpg',
    author: 'Subray Hegde',
    licence: 'CC BY 1.0',
    licenceUrl: 'https://creativecommons.org/licenses/by/1.0',
    source:
      'https://commons.wikimedia.org/wiki/File:Garcinia_indica_-_fruits,_seeds,_pulp_and_rinds.jpg',
  },
  {
    key: 'lemon',
    label: 'Lemon',
    title: 'Lemon.png',
    author: 'Aka and Dr.Intobesa',
    licence: 'CC BY-SA 2.5',
    licenceUrl: 'https://creativecommons.org/licenses/by-sa/2.5',
    source: 'https://commons.wikimedia.org/wiki/File:Lemon.png',
  },
  {
    key: 'lemongrass',
    label: 'Lemongrass',
    title: 'Tanglad (lemongrass, Cymbopogon citratus) - Philippines.jpg',
    author: 'Obsidian Soul',
    licence: 'CC0',
    licenceUrl: 'http://creativecommons.org/publicdomain/zero/1.0/deed.en',
    source:
      'https://commons.wikimedia.org/wiki/File:Tanglad_(lemongrass,_Cymbopogon_citratus)_-_Philippines.jpg',
  },
  {
    key: 'limca',
    label: 'Limca',
    title: 'Limca bottles.jpg',
    author: 'FOTOMEYLE',
    licence: 'CC BY 2.0',
    licenceUrl: 'https://creativecommons.org/licenses/by/2.0',
    source: 'https://commons.wikimedia.org/wiki/File:Limca_bottles.jpg',
  },
  {
    key: 'lime',
    label: 'Lime',
    title: 'Citrus lime.png',
    author: 'The original Uploader was Oven Fresh at English Wikipedia',
    licence: 'Public domain',
    licenceUrl: '',
    source: 'https://commons.wikimedia.org/wiki/File:Citrus_lime.png',
  },
  {
    key: 'liqueur',
    label: 'Liqueur',
    title: 'Midori Melon Liqueur 01.jpg',
    author: 'Indrajit Das',
    licence: 'CC BY-SA 4.0',
    licenceUrl: 'https://creativecommons.org/licenses/by-sa/4.0',
    source: 'https://commons.wikimedia.org/wiki/File:Midori_Melon_Liqueur_01.jpg',
  },
  {
    key: 'magic-moments',
    label: 'Magic Moments',
    title: 'Magic Moments Vodka.jpg',
    author: 'Deepak G Goswami',
    licence: 'CC BY-SA 3.0',
    licenceUrl: 'https://creativecommons.org/licenses/by-sa/3.0',
    source: 'https://commons.wikimedia.org/wiki/File:Magic_Moments_Vodka.jpg',
  },
  {
    key: 'maida',
    label: 'White flour (maida)',
    title: 'All-Purpose Flour (4107895947).jpg',
    author: 'Veganbaking.net from USA',
    licence: 'CC BY-SA 2.0',
    licenceUrl: 'https://creativecommons.org/licenses/by-sa/2.0',
    source: 'https://commons.wikimedia.org/wiki/File:All-Purpose_Flour_(4107895947).jpg',
  },
  {
    key: 'mango',
    label: 'Mango',
    title: 'Mango on a white background.png',
    author: 'Ninjatacoshell',
    licence: 'CC BY-SA 3.0',
    licenceUrl: 'https://creativecommons.org/licenses/by-sa/3.0',
    source: 'https://commons.wikimedia.org/wiki/File:Mango_on_a_white_background.png',
  },
  {
    key: 'mansion-house',
    label: 'Mansion House',
    title: 'Mansion House Brandy.JPG',
    author: 'Veera.sj',
    licence: 'CC0',
    licenceUrl: 'http://creativecommons.org/publicdomain/zero/1.0/deed.en',
    source: 'https://commons.wikimedia.org/wiki/File:Mansion_House_Brandy.JPG',
  },
  {
    key: 'martini',
    label: 'Martini vermouth',
    title: 'MartiniBianco&Rosso.JPG',
    author: 'Metsavend',
    licence: 'CC BY-SA 2.5',
    licenceUrl: 'https://creativecommons.org/licenses/by-sa/2.5',
    source: 'https://commons.wikimedia.org/wiki/File:MartiniBianco%26Rosso.JPG',
  },
  {
    key: 'masala-paste',
    label: 'Masala paste',
    title: 'Ginger Garlic Paste.jpg',
    author: 'Krunal7777',
    licence: 'CC BY-SA 4.0',
    licenceUrl: 'https://creativecommons.org/licenses/by-sa/4.0',
    source: 'https://commons.wikimedia.org/wiki/File:Ginger_Garlic_Paste.jpg',
  },
  {
    key: 'masoor-dal',
    label: 'Masoor dal',
    title: 'Red lentils Gogreen.jpg',
    author: 'Tiia Monto',
    licence: 'CC BY-SA 4.0',
    licenceUrl: 'https://creativecommons.org/licenses/by-sa/4.0',
    source: 'https://commons.wikimedia.org/wiki/File:Red_lentils_Gogreen.jpg',
  },
  {
    key: 'mayonnaise',
    label: 'Mayonnaise',
    title: 'Mayonnaise Jar 550x900.JPG',
    author: 'Wikimedia Commons',
    licence: 'Public domain',
    licenceUrl: '',
    source: 'https://commons.wikimedia.org/wiki/File:Mayonnaise_Jar_550x900.JPG',
  },
  {
    key: 'mcdowells',
    label: "McDowell's No.1",
    title: 'Mc Dowell No. 1 Rum.jpg',
    author: 'Pinakpani',
    licence: 'CC BY-SA 4.0',
    licenceUrl: 'https://creativecommons.org/licenses/by-sa/4.0',
    source: 'https://commons.wikimedia.org/wiki/File:Mc_Dowell_No._1_Rum.jpg',
  },
  {
    key: 'meat',
    label: 'Meat',
    title: 'Raw beef.jpg',
    author: 'Halima Waziri',
    licence: 'CC BY-SA 4.0',
    licenceUrl: 'https://creativecommons.org/licenses/by-sa/4.0',
    source: 'https://commons.wikimedia.org/wiki/File:Raw_beef.jpg',
  },
  {
    key: 'minibar',
    label: 'Minibar',
    title: 'Hotel room minibar.jpg',
    author: 'Mcrociani',
    licence: 'CC BY-SA 3.0',
    licenceUrl: 'https://creativecommons.org/licenses/by-sa/3.0',
    source: 'https://commons.wikimedia.org/wiki/File:Hotel_room_minibar.jpg',
  },
  {
    key: 'mint',
    label: 'Mint leaves',
    title: 'CSA-Chocolate-Mint.jpg',
    author: 'Evan-Amos',
    licence: 'Public domain',
    licenceUrl: '',
    source: 'https://commons.wikimedia.org/wiki/File:CSA-Chocolate-Mint.jpg',
  },
  {
    key: 'mixers',
    label: 'Mixers',
    title: 'Soft drinks.jpg',
    author: 'Challiyan',
    licence: 'CC BY-SA 3.0',
    licenceUrl: 'https://creativecommons.org/licenses/by-sa/3.0',
    source: 'https://commons.wikimedia.org/wiki/File:Soft_drinks.jpg',
  },
  {
    key: 'moet',
    label: 'Moët & Chandon',
    title: 'Moët & Chandon - 001.jpg',
    author: 'Mutari 21:12, 31 March 2008 (UTC)',
    licence: 'Public domain',
    licenceUrl: '',
    source: 'https://commons.wikimedia.org/wiki/File:Mo%C3%ABt_%26_Chandon_-_001.jpg',
  },
  {
    key: 'moong-dal',
    label: 'Moong dal',
    title: 'Green Moong Dal.jpg',
    author: 'Gaurav Dhwaj Khadka',
    licence: 'CC BY-SA 4.0',
    licenceUrl: 'https://creativecommons.org/licenses/by-sa/4.0',
    source: 'https://commons.wikimedia.org/wiki/File:Green_Moong_Dal.jpg',
  },
  {
    key: 'mountain-dew',
    label: 'Mountain Dew',
    title: 'Mountain Dew Flasche (cropped).jpg',
    author: 'DYVER',
    licence: 'CC BY-SA 4.0',
    licenceUrl: 'https://creativecommons.org/licenses/by-sa/4.0',
    source: 'https://commons.wikimedia.org/wiki/File:Mountain_Dew_Flasche_(cropped).jpg',
  },
  {
    key: 'mushroom',
    label: 'Mushroom',
    title: 'Baby-Port-Mushrooms.jpg',
    author: 'Evan-Amos',
    licence: 'Public domain',
    licenceUrl: '',
    source: 'https://commons.wikimedia.org/wiki/File:Baby-Port-Mushrooms.jpg',
  },
  {
    key: 'muskmelon',
    label: 'Muskmelon',
    title: 'Cantaloupe Melon cross section.png',
    author: 'Sangfroid',
    licence: 'Public domain',
    licenceUrl: '',
    source: 'https://commons.wikimedia.org/wiki/File:Cantaloupe_Melon_cross_section.png',
  },
  {
    key: 'mustard-oil',
    label: 'Mustard oil',
    title: 'Dune Aura Mustard oil bottle picture.jpg',
    author: 'Dunesaura',
    licence: 'CC BY 4.0',
    licenceUrl: 'https://creativecommons.org/licenses/by/4.0',
    source: 'https://commons.wikimedia.org/wiki/File:Dune_Aura_Mustard_oil_bottle_picture.jpg',
  },
  {
    key: 'mustard-seeds',
    label: 'Mustard seeds',
    title: 'Black mustard seeds.jpg',
    author: 'Theredgiant',
    licence: 'CC BY-SA 4.0',
    licenceUrl: 'https://creativecommons.org/licenses/by-sa/4.0',
    source: 'https://commons.wikimedia.org/wiki/File:Black_mustard_seeds.jpg',
  },
  {
    key: 'mutton',
    label: 'Mutton',
    title: 'Raw lamb cutlets with shredded ginger and rosemary.jpg',
    author: 'Photo by User:Salimfadhley',
    licence: 'CC BY-SA 3.0',
    licenceUrl: 'http://creativecommons.org/licenses/by-sa/3.0/',
    source:
      'https://commons.wikimedia.org/wiki/File:Raw_lamb_cutlets_with_shredded_ginger_and_rosemary.jpg',
  },
  {
    key: 'nachos',
    label: 'Nacho chips',
    title: 'Tortilla Chips.jpg',
    author: 'Gaurav Dhwaj Khadka',
    licence: 'CC BY-SA 4.0',
    licenceUrl: 'https://creativecommons.org/licenses/by-sa/4.0',
    source: 'https://commons.wikimedia.org/wiki/File:Tortilla_Chips.jpg',
  },
  {
    key: 'nescafe',
    label: 'Nescafé',
    title: 'Nescafè instant coffee, 2019-(01).jpg',
    author: 'T. Koch',
    licence: 'CC BY-SA 4.0',
    licenceUrl: 'https://creativecommons.org/licenses/by-sa/4.0',
    source: 'https://commons.wikimedia.org/wiki/File:Nescaf%C3%A8_instant_coffee,_2019-(01).jpg',
  },
  {
    key: 'nutella',
    label: 'Nutella',
    title: 'Nutella ak.jpg',
    author: '-donald-',
    licence: 'CC BY-SA 3.0',
    licenceUrl: 'http://creativecommons.org/licenses/by-sa/3.0/',
    source: 'https://commons.wikimedia.org/wiki/File:Nutella_ak.jpg',
  },
  {
    key: 'oats',
    label: 'Oats',
    title: 'Rolled oats.jpg',
    author: 'en:user:Hankwang',
    licence: 'Public domain',
    licenceUrl: '',
    source: 'https://commons.wikimedia.org/wiki/File:Rolled_oats.jpg',
  },
  {
    key: 'officers-choice',
    label: "Officer's Choice",
    title: "Officer's Choice Prestige Whiskey.jpg",
    author: 'abhiriksh',
    licence: 'CC BY-SA 3.0',
    licenceUrl: 'https://creativecommons.org/licenses/by-sa/3.0',
    source: 'https://commons.wikimedia.org/wiki/File:Officer%27s_Choice_Prestige_Whiskey.jpg',
  },
  {
    key: 'oil',
    label: 'Cooking oil',
    title: 'Sunflower oil.jpg',
    author: 'Tiia Monto',
    licence: 'CC BY-SA 4.0',
    licenceUrl: 'https://creativecommons.org/licenses/by-sa/4.0',
    source: 'https://commons.wikimedia.org/wiki/File:Sunflower_oil.jpg',
  },
  {
    key: 'okra',
    label: 'Okra',
    title: 'Fresh okra (1).jpg',
    author: 'Fumikas Sagisavas',
    licence: 'CC0',
    licenceUrl: 'http://creativecommons.org/publicdomain/zero/1.0/deed.en',
    source: 'https://commons.wikimedia.org/wiki/File:Fresh_okra_(1).jpg',
  },
  {
    key: 'old-monk',
    label: 'Old Monk',
    title: 'Old monk rum bottle.jpg',
    author: 'Psubhashish',
    licence: 'CC BY-SA 3.0',
    licenceUrl: 'https://creativecommons.org/licenses/by-sa/3.0',
    source: 'https://commons.wikimedia.org/wiki/File:Old_monk_rum_bottle.jpg',
  },
  {
    key: 'olive',
    label: 'Olives',
    title: 'Green olives.jpg',
    author: 'Renee Comet (Photographer)',
    licence: 'Public domain',
    licenceUrl: '',
    source: 'https://commons.wikimedia.org/wiki/File:Green_olives.jpg',
  },
  {
    key: 'olive-oil',
    label: 'Olive oil',
    title: 'Bottle of Extra Virgin Olive Oil.jpg',
    author: 'Mervat Salman',
    licence: 'CC BY-SA 4.0',
    licenceUrl: 'https://creativecommons.org/licenses/by-sa/4.0',
    source: 'https://commons.wikimedia.org/wiki/File:Bottle_of_Extra_Virgin_Olive_Oil.jpg',
  },
  {
    key: 'onion',
    label: 'Onion',
    title: 'Red Onion on White.JPG',
    author: 'Colin',
    licence: 'CC BY-SA 3.0',
    licenceUrl: 'https://creativecommons.org/licenses/by-sa/3.0',
    source: 'https://commons.wikimedia.org/wiki/File:Red_Onion_on_White.JPG',
  },
  {
    key: 'orange',
    label: 'Orange',
    title: 'Perpendicular orange.png',
    author: 'Ekko',
    licence: 'CC BY 2.5',
    licenceUrl: 'https://creativecommons.org/licenses/by/2.5',
    source: 'https://commons.wikimedia.org/wiki/File:Perpendicular_orange.png',
  },
  {
    key: 'orange-juice',
    label: 'Orange juice',
    title: 'Orange juice 1 edit1.jpg',
    author: 'Agency of the United States Department of Agriculture Edited Version by: Arad',
    licence: 'Public domain',
    licenceUrl: '',
    source: 'https://commons.wikimedia.org/wiki/File:Orange_juice_1_edit1.jpg',
  },
  {
    key: 'oreo',
    label: 'Oreo',
    title: 'Oreo-Two-Cookies.jpg',
    author: 'Evan-Amos',
    licence: 'Public domain',
    licenceUrl: '',
    source: 'https://commons.wikimedia.org/wiki/File:Oreo-Two-Cookies.jpg',
  },
  {
    key: 'packaging',
    label: 'Packaging',
    title: 'Food container.jpg',
    author: 'Сергей Михель',
    licence: 'CC0',
    licenceUrl: 'http://creativecommons.org/publicdomain/zero/1.0/deed.en',
    source: 'https://commons.wikimedia.org/wiki/File:Food_container.jpg',
  },
  {
    key: 'paneer',
    label: 'Paneer',
    title: 'Homemade Paneer cottage cheese cut into cubes.JPG',
    author: 'Nithyasrm',
    licence: 'CC BY-SA 4.0',
    licenceUrl: 'https://creativecommons.org/licenses/by-sa/4.0',
    source:
      'https://commons.wikimedia.org/wiki/File:Homemade_Paneer_cottage_cheese_cut_into_cubes.JPG',
  },
  {
    key: 'papaya',
    label: 'Papaya',
    title: 'Papaya - longitudinal section.jpg',
    author: 'Ivar Leidus',
    licence: 'CC BY-SA 4.0',
    licenceUrl: 'https://creativecommons.org/licenses/by-sa/4.0',
    source: 'https://commons.wikimedia.org/wiki/File:Papaya_-_longitudinal_section.jpg',
  },
  {
    key: 'paper-bag',
    label: 'Paper bag',
    title: 'Brown Bag (with staple).jpg',
    author: 'Jeffrey Beall',
    licence: 'CC BY-SA 2.0',
    licenceUrl: 'https://creativecommons.org/licenses/by-sa/2.0',
    source: 'https://commons.wikimedia.org/wiki/File:Brown_Bag_(with_staple).jpg',
  },
  {
    key: 'paper-cup',
    label: 'Paper cup',
    title: 'Paper Cups - isolated.png',
    author: 'Alanthebox',
    licence: 'CC0',
    licenceUrl: 'http://creativecommons.org/publicdomain/zero/1.0/deed.en',
    source: 'https://commons.wikimedia.org/wiki/File:Paper_Cups_-_isolated.png',
  },
  {
    key: 'paper-napkins',
    label: 'Paper napkins',
    title: 'Napkins - isolated.png',
    author: 'Alanthebox',
    licence: 'CC0',
    licenceUrl: 'http://creativecommons.org/publicdomain/zero/1.0/deed.en',
    source: 'https://commons.wikimedia.org/wiki/File:Napkins_-_isolated.png',
  },
  {
    key: 'pasta',
    label: 'Pasta',
    title: 'Pasta.jpg',
    author: 'Daniel K. Gebhart',
    licence: 'CC BY 2.5',
    licenceUrl: 'https://creativecommons.org/licenses/by/2.5',
    source: 'https://commons.wikimedia.org/wiki/File:Pasta.jpg',
  },
  {
    key: 'patron',
    label: 'Patrón',
    title: 'PatronGoldBottle.jpg',
    author: 'Broncinbuck at English Wikipedia',
    licence: 'CC BY-SA 3.0',
    licenceUrl: 'http://creativecommons.org/licenses/by-sa/3.0/',
    source: 'https://commons.wikimedia.org/wiki/File:PatronGoldBottle.jpg',
  },
  {
    key: 'paul-john',
    label: 'Paul John',
    title: 'Brilliance Single Malt Whisky from Paul John.png',
    author: 'John Distilleries',
    licence: 'CC BY-SA 4.0',
    licenceUrl: 'https://creativecommons.org/licenses/by-sa/4.0',
    source:
      'https://commons.wikimedia.org/wiki/File:Brilliance_Single_Malt_Whisky_from_Paul_John.png',
  },
  {
    key: 'peach',
    label: 'Peach',
    title: 'Peaches.png',
    author: 'eommina',
    licence: 'CC0',
    licenceUrl: 'http://creativecommons.org/publicdomain/zero/1.0/deed.en',
    source: 'https://commons.wikimedia.org/wiki/File:Peaches.png',
  },
  {
    key: 'peanuts',
    label: 'Peanuts',
    title: 'Groundnuts in container.jpg',
    author: 'Ibn Dagara',
    licence: 'CC BY-SA 4.0',
    licenceUrl: 'https://creativecommons.org/licenses/by-sa/4.0',
    source: 'https://commons.wikimedia.org/wiki/File:Groundnuts_in_container.jpg',
  },
  {
    key: 'pear',
    label: 'Pear',
    title: 'Golden Asian Pear 2.png',
    author: 'TylerMascola',
    licence: 'CC0',
    licenceUrl: 'http://creativecommons.org/publicdomain/zero/1.0/deed.en',
    source: 'https://commons.wikimedia.org/wiki/File:Golden_Asian_Pear_2.png',
  },
  {
    key: 'peas',
    label: 'Green peas',
    title: 'NCI peas in pod.jpg',
    author: 'Renee Comet (photographer) AV Number: AV-9400-4164',
    licence: 'Public domain',
    licenceUrl: '',
    source: 'https://commons.wikimedia.org/wiki/File:NCI_peas_in_pod.jpg',
  },
  {
    key: 'pepsi',
    label: 'Pepsi',
    title: 'Pepsi Bottle.jpg',
    author: 'Ayakln',
    licence: 'CC BY-SA 4.0',
    licenceUrl: 'https://creativecommons.org/licenses/by-sa/4.0',
    source: 'https://commons.wikimedia.org/wiki/File:Pepsi_Bottle.jpg',
  },
  {
    key: 'pillow',
    label: 'Pillow and cover',
    title: 'An average white pillow.jpg',
    author: '0hAerqplane',
    licence: 'CC BY-SA 4.0',
    licenceUrl: 'https://creativecommons.org/licenses/by-sa/4.0',
    source: 'https://commons.wikimedia.org/wiki/File:An_average_white_pillow.jpg',
  },
  {
    key: 'pineapple',
    label: 'Pineapple',
    title: 'Ananas~May 2008-1.jpg',
    author: 'Alvesgaspar',
    licence: 'CC BY-SA 3.0',
    licenceUrl: 'https://creativecommons.org/licenses/by-sa/3.0',
    source: 'https://commons.wikimedia.org/wiki/File:Ananas~May_2008-1.jpg',
  },
  {
    key: 'poha',
    label: 'Flattened rice (poha)',
    title: 'Flattened rice.jpg',
    author: 'Mashkawat.ahsan',
    licence: 'CC BY-SA 4.0',
    licenceUrl: 'https://creativecommons.org/licenses/by-sa/4.0',
    source: 'https://commons.wikimedia.org/wiki/File:Flattened_rice.jpg',
  },
  {
    key: 'pomegranate',
    label: 'Pomegranate',
    title: 'Pomegranate on white.jpg',
    author: 'Rhododendrites',
    licence: 'CC BY-SA 4.0',
    licenceUrl: 'https://creativecommons.org/licenses/by-sa/4.0',
    source: 'https://commons.wikimedia.org/wiki/File:Pomegranate_on_white.jpg',
  },
  {
    key: 'pool-chlorine',
    label: 'Pool chlorine',
    title: 'Liquid Pool Chlorine.jpg',
    author: 'Maksym Kozlenko',
    licence: 'CC BY-SA 4.0',
    licenceUrl: 'https://creativecommons.org/licenses/by-sa/4.0',
    source: 'https://commons.wikimedia.org/wiki/File:Liquid_Pool_Chlorine.jpg',
  },
  {
    key: 'pool-towel',
    label: 'Pool towel',
    title: 'Towels.JPG',
    author: 'Doronef',
    licence: 'Public domain',
    licenceUrl: '',
    source: 'https://commons.wikimedia.org/wiki/File:Towels.JPG',
  },
  {
    key: 'popcorn',
    label: 'Popcorn',
    title: 'Popcorn 1.jpg',
    author: 'Gaurav Dhwaj Khadka',
    licence: 'CC BY-SA 4.0',
    licenceUrl: 'https://creativecommons.org/licenses/by-sa/4.0',
    source: 'https://commons.wikimedia.org/wiki/File:Popcorn_1.jpg',
  },
  {
    key: 'potato',
    label: 'Potato',
    title: 'Potato cv Dejima (cropped).jpg',
    author: 'Fk',
    licence: 'CC BY-SA 4.0',
    licenceUrl: 'https://creativecommons.org/licenses/by-sa/4.0',
    source: 'https://commons.wikimedia.org/wiki/File:Potato_cv_Dejima_(cropped).jpg',
  },
  {
    key: 'prawns',
    label: 'Prawns',
    title: 'Raw shrimp.jpg',
    author: 'Fumikas Sagisavas',
    licence: 'CC0',
    licenceUrl: 'http://creativecommons.org/publicdomain/zero/1.0/deed.en',
    source: 'https://commons.wikimedia.org/wiki/File:Raw_shrimp.jpg',
  },
  {
    key: 'pringles',
    label: 'Pringles',
    title: 'Pringles chips.JPG',
    author: 'Glane23',
    licence: 'CC BY-SA 3.0',
    licenceUrl: 'https://creativecommons.org/licenses/by-sa/3.0',
    source: 'https://commons.wikimedia.org/wiki/File:Pringles_chips.JPG',
  },
  {
    key: 'pumpkin',
    label: 'Pumpkin',
    title: 'Calabaza CDC.jpg',
    author: 'Wikimedia Commons',
    licence: 'Public domain',
    licenceUrl: '',
    source: 'https://commons.wikimedia.org/wiki/File:Calabaza_CDC.jpg',
  },
  {
    key: 'radish',
    label: 'Radish',
    title: 'Radish 2.png',
    author: 'Tiia Monto',
    licence: 'CC BY 4.0',
    licenceUrl: 'https://creativecommons.org/licenses/by/4.0',
    source: 'https://commons.wikimedia.org/wiki/File:Radish_2.png',
  },
  {
    key: 'raisins',
    label: 'Raisins',
    title: 'Raisins 01.jpg',
    author: 'Paweł Kuźniar (Jojo_1, Jojo)',
    licence: 'CC BY-SA 3.0',
    licenceUrl: 'http://creativecommons.org/licenses/by-sa/3.0/',
    source: 'https://commons.wikimedia.org/wiki/File:Raisins_01.jpg',
  },
  {
    key: 'rajma',
    label: 'Kidney beans (rajma)',
    title: 'Red kidney beans.jpg',
    author: 'Fumikas Sagisavas',
    licence: 'CC0',
    licenceUrl: 'http://creativecommons.org/publicdomain/zero/1.0/deed.en',
    source: 'https://commons.wikimedia.org/wiki/File:Red_kidney_beans.jpg',
  },
  {
    key: 'red-chilli',
    label: 'Fresh red chilli',
    title: "'Red chilli.jpg",
    author: 'Arivumathi',
    licence: 'CC0',
    licenceUrl: 'http://creativecommons.org/publicdomain/zero/1.0/deed.en',
    source: 'https://commons.wikimedia.org/wiki/File:%27Red_chilli.jpg',
  },
  {
    key: 'red-rice',
    label: 'Red rice',
    title: 'Red rice.jpg',
    author: 'Uday patel zz',
    licence: 'CC BY-SA 4.0',
    licenceUrl: 'https://creativecommons.org/licenses/by-sa/4.0',
    source: 'https://commons.wikimedia.org/wiki/File:Red_rice.jpg',
  },
  {
    key: 'red-wine',
    label: 'Red wine',
    title: 'French beaujolais red wine bottle.jpg',
    author: 'Lewis Ronald',
    licence: 'CC BY-SA 3.0',
    licenceUrl: 'https://creativecommons.org/licenses/by-sa/3.0',
    source: 'https://commons.wikimedia.org/wiki/File:French_beaujolais_red_wine_bottle.jpg',
  },
  {
    key: 'remy-martin',
    label: 'Rémy Martin',
    title: 'Rémy Martin VSOP.jpg',
    author: 'SKopp',
    licence: 'CC BY 4.0',
    licenceUrl: 'https://creativecommons.org/licenses/by/4.0',
    source: 'https://commons.wikimedia.org/wiki/File:R%C3%A9my_Martin_VSOP.jpg',
  },
  {
    key: 'rice',
    label: 'Rice',
    title: 'Basmati Rice India, raw.jpg',
    author: 'cookbookman17',
    licence: 'CC BY 2.0',
    licenceUrl: 'https://creativecommons.org/licenses/by/2.0',
    source: 'https://commons.wikimedia.org/wiki/File:Basmati_Rice_India,_raw.jpg',
  },
  {
    key: 'rice-flour',
    label: 'Rice flour',
    title: 'Rice flour.jpg',
    author: 'Thamizhpparithi Maari',
    licence: 'CC BY-SA 4.0',
    licenceUrl: 'https://creativecommons.org/licenses/by-sa/4.0',
    source: 'https://commons.wikimedia.org/wiki/File:Rice_flour.jpg',
  },
  {
    key: 'rose',
    label: 'Rose petals',
    title: 'Dried rose petals.jpg',
    author: 'Fumikas Sagisavas',
    licence: 'CC0',
    licenceUrl: 'http://creativecommons.org/publicdomain/zero/1.0/deed.en',
    source: 'https://commons.wikimedia.org/wiki/File:Dried_rose_petals.jpg',
  },
  {
    key: 'royal-stag',
    label: 'Royal Stag',
    title: 'Royal stag wishky .jpg',
    author: 'Kanhaiyalal Chouhan',
    licence: 'CC BY 4.0',
    licenceUrl: 'https://creativecommons.org/licenses/by/4.0',
    source: 'https://commons.wikimedia.org/wiki/File:Royal_stag_wishky_.jpg',
  },
  {
    key: 'saffron',
    label: 'Saffron',
    title: 'Iran saffron threads.jpg',
    author: 'Rainer Zenz',
    licence: 'Public domain',
    licenceUrl: '',
    source: 'https://commons.wikimedia.org/wiki/File:Iran_saffron_threads.jpg',
  },
  {
    key: 'salt',
    label: 'Salt',
    title: 'Salt shaker on white background.jpg',
    author: 'Dubravko Sorić SoraZG on Flickr',
    licence: 'CC BY 2.0',
    licenceUrl: 'https://creativecommons.org/licenses/by/2.0',
    source: 'https://commons.wikimedia.org/wiki/File:Salt_shaker_on_white_background.jpg',
  },
  {
    key: 'sanitary-bag',
    label: 'Sanitary bag',
    title: 'CRH Sanitary Bag.jpeg',
    author: 'Richard923888',
    licence: 'CC BY-SA 3.0',
    licenceUrl: 'https://creativecommons.org/licenses/by-sa/3.0',
    source: 'https://commons.wikimedia.org/wiki/File:CRH_Sanitary_Bag.jpeg',
  },
  {
    key: 'sausage',
    label: 'Sausages (chouriço)',
    title: 'Chorizo sausage.JPG',
    author: 'Jaydoo',
    licence: 'CC BY-SA 3.0',
    licenceUrl: 'https://creativecommons.org/licenses/by-sa/3.0',
    source: 'https://commons.wikimedia.org/wiki/File:Chorizo_sausage.JPG',
  },
  {
    key: 'schweppes',
    label: 'Schweppes',
    title: 'Schweppes bottles.jpg',
    author: 'Evers (talk)',
    licence: 'CC BY 3.0',
    licenceUrl: 'https://creativecommons.org/licenses/by/3.0',
    source: 'https://commons.wikimedia.org/wiki/File:Schweppes_bottles.jpg',
  },
  {
    key: 'seafood',
    label: 'Seafood',
    title: 'Fresh Seafood.jpg',
    author: 'Petr Kratochvil',
    licence: 'CC0',
    licenceUrl: 'http://creativecommons.org/publicdomain/zero/1.0/deed.en',
    source: 'https://commons.wikimedia.org/wiki/File:Fresh_Seafood.jpg',
  },
  {
    key: 'semolina',
    label: 'Semolina (rava)',
    title: 'Semolina 300260.jpg',
    author: 'Rillke',
    licence: 'CC BY-SA 3.0 de',
    licenceUrl: 'https://creativecommons.org/licenses/by-sa/3.0/de/deed.en',
    source: 'https://commons.wikimedia.org/wiki/File:Semolina_300260.jpg',
  },
  {
    key: 'sesame',
    label: 'Sesame seeds',
    title: 'Sa white sesame seeds.jpg',
    author: 'Sanjay ach',
    licence: 'CC BY-SA 3.0',
    licenceUrl: 'http://creativecommons.org/licenses/by-sa/3.0/',
    source: 'https://commons.wikimedia.org/wiki/File:Sa_white_sesame_seeds.jpg',
  },
  {
    key: 'seven-up',
    label: '7UP',
    title: '7UP Bottle.jpg',
    author: 'Aurelio de Sandoval',
    licence: 'CC BY-SA 2.5 mx',
    licenceUrl: 'https://creativecommons.org/licenses/by-sa/2.5/mx/deed.en',
    source: 'https://commons.wikimedia.org/wiki/File:7UP_Bottle.jpg',
  },
  {
    key: 'shampoo',
    label: 'Shampoo and lotion',
    title: 'Green shampoo bottle.jpg',
    author: 'Mezoneni',
    licence: 'CC BY-SA 4.0',
    licenceUrl: 'https://creativecommons.org/licenses/by-sa/4.0',
    source: 'https://commons.wikimedia.org/wiki/File:Green_shampoo_bottle.jpg',
  },
  {
    key: 'shaving-kit',
    label: 'Shaving kit',
    title: 'Chrome-Safety-Razor.jpg',
    author: 'Evan-Amos',
    licence: 'Public domain',
    licenceUrl: '',
    source: 'https://commons.wikimedia.org/wiki/File:Chrome-Safety-Razor.jpg',
  },
  {
    key: 'single-malt',
    label: 'Single malt',
    title: 'Lagavulin Single Malt Scotch Whisky Aged 16 Years.jpg',
    author: 'Amitbalani',
    licence: 'CC0',
    licenceUrl: 'http://creativecommons.org/publicdomain/zero/1.0/deed.en',
    source:
      'https://commons.wikimedia.org/wiki/File:Lagavulin_Single_Malt_Scotch_Whisky_Aged_16_Years.jpg',
  },
  {
    key: 'slippers',
    label: 'Slippers',
    title: 'Taiwanese blue slippers.jpg',
    author: 'Peachyeung316',
    licence: 'CC BY-SA 4.0',
    licenceUrl: 'https://creativecommons.org/licenses/by-sa/4.0',
    source: 'https://commons.wikimedia.org/wiki/File:Taiwanese_blue_slippers.jpg',
  },
  {
    key: 'smirnoff',
    label: 'Smirnoff',
    title: 'Smirnoff 70cl bottle.jpg',
    author: 'User Mathias Rodstedt on sv.wikipedia',
    licence: 'CC BY-SA 3.0',
    licenceUrl: 'http://creativecommons.org/licenses/by-sa/3.0/',
    source: 'https://commons.wikimedia.org/wiki/File:Smirnoff_70cl_bottle.jpg',
  },
  {
    key: 'soap',
    label: 'Soap',
    title: 'A bar of soap.jpg',
    author: 'Lacrimosus',
    licence: 'Public domain',
    licenceUrl: '',
    source: 'https://commons.wikimedia.org/wiki/File:A_bar_of_soap.jpg',
  },
  {
    key: 'soy-sauce',
    label: 'Soy sauce',
    title: 'Kikkoman Soy Sauce, Front-view jp-type ,.jpg',
    author: 'Mj-bird',
    licence: 'CC BY-SA 3.0',
    licenceUrl: 'https://creativecommons.org/licenses/by-sa/3.0',
    source: 'https://commons.wikimedia.org/wiki/File:Kikkoman_Soy_Sauce,_Front-view_jp-type_,.jpg',
  },
  {
    key: 'sparkling-wine',
    label: 'Sparkling wine',
    title: 'Champagne bottle, 2015-(01).jpg',
    author: 'Simon Cocks',
    licence: 'CC BY 2.0',
    licenceUrl: 'https://creativecommons.org/licenses/by/2.0',
    source: 'https://commons.wikimedia.org/wiki/File:Champagne_bottle,_2015-(01).jpg',
  },
  {
    key: 'spices',
    label: 'Spices',
    title: 'Indian Spices.jpg',
    author: 'Joe mon bkk',
    licence: 'CC BY-SA 4.0',
    licenceUrl: 'https://creativecommons.org/licenses/by-sa/4.0',
    source: 'https://commons.wikimedia.org/wiki/File:Indian_Spices.jpg',
  },
  {
    key: 'spinach',
    label: 'Spinach and leafy greens',
    title: 'Collard-Greens-Bundle.jpg',
    author: 'Evan-Amos',
    licence: 'Public domain',
    licenceUrl: '',
    source: 'https://commons.wikimedia.org/wiki/File:Collard-Greens-Bundle.jpg',
  },
  {
    key: 'spirits',
    label: 'Spirits bottle',
    title: 'Liquor bottles.jpg',
    author: 'scottfeldstein',
    licence: 'CC BY 2.0',
    licenceUrl: 'https://creativecommons.org/licenses/by/2.0',
    source: 'https://commons.wikimedia.org/wiki/File:Liquor_bottles.jpg',
  },
  {
    key: 'sponge',
    label: 'Sponge and scrubber',
    title: 'Sponge on white background.jpg',
    author: 'Pascua Theus alias Körnerbrötchen, white background by Amada44',
    licence: 'CC BY-SA 2.0 de',
    licenceUrl: 'https://creativecommons.org/licenses/by-sa/2.0/de/deed.en',
    source: 'https://commons.wikimedia.org/wiki/File:Sponge_on_white_background.jpg',
  },
  {
    key: 'spring-onion',
    label: 'Spring onion',
    title: 'CSA-Red-Spring-Onions.jpg',
    author: 'Evan-Amos',
    licence: 'Public domain',
    licenceUrl: '',
    source: 'https://commons.wikimedia.org/wiki/File:CSA-Red-Spring-Onions.jpg',
  },
  {
    key: 'sprite',
    label: 'Sprite',
    title: 'Sprite Glass Bottle.jpg',
    author: 'Ayakln',
    licence: 'CC BY-SA 4.0',
    licenceUrl: 'https://creativecommons.org/licenses/by-sa/4.0',
    source: 'https://commons.wikimedia.org/wiki/File:Sprite_Glass_Bottle.jpg',
  },
  {
    key: 'squid',
    label: 'Squid',
    title: 'Frozen fresh squid.jpg',
    author: 'Fumikas Sagisavas',
    licence: 'CC0',
    licenceUrl: 'http://creativecommons.org/publicdomain/zero/1.0/deed.en',
    source: 'https://commons.wikimedia.org/wiki/File:Frozen_fresh_squid.jpg',
  },
  {
    key: 'star-anise',
    label: 'Star anise',
    title: 'Dried Star Anise Fruit Seeds.jpg',
    author: 'Sanjay Acharya',
    licence: 'CC BY-SA 4.0',
    licenceUrl: 'https://creativecommons.org/licenses/by-sa/4.0',
    source: 'https://commons.wikimedia.org/wiki/File:Dried_Star_Anise_Fruit_Seeds.jpg',
  },
  {
    key: 'stella-artois',
    label: 'Stella Artois',
    title: 'Stella Artois bottle.jpg',
    author: 'Kimjon12',
    licence: 'CC BY-SA 4.0',
    licenceUrl: 'https://creativecommons.org/licenses/by-sa/4.0',
    source: 'https://commons.wikimedia.org/wiki/File:Stella_Artois_bottle.jpg',
  },
  {
    key: 'strawberry',
    label: 'Strawberry',
    title: 'A strawberry with achene.jpg',
    author: 'Renee Comet (Photographer)',
    licence: 'Public domain',
    licenceUrl: '',
    source: 'https://commons.wikimedia.org/wiki/File:A_strawberry_with_achene.jpg',
  },
  {
    key: 'sugar',
    label: 'Sugar',
    title: 'Bowl of white sugar.jpg',
    author: 'Douglas P Perkins',
    licence: 'CC BY 3.0',
    licenceUrl: 'https://creativecommons.org/licenses/by/3.0',
    source: 'https://commons.wikimedia.org/wiki/File:Bowl_of_white_sugar.jpg',
  },
  {
    key: 'sula',
    label: 'Sula',
    title: 'Sula Sparkling Shiraz.jpg',
    author: 'Princerocky2021',
    licence: 'CC BY-SA 4.0',
    licenceUrl: 'https://creativecommons.org/licenses/by-sa/4.0',
    source: 'https://commons.wikimedia.org/wiki/File:Sula_Sparkling_Shiraz.jpg',
  },
  {
    key: 'sweet-potato',
    label: 'Sweet potato',
    title: 'SweetPotato.jpg',
    author: 'Petr Kratochvil',
    licence: 'Attribution',
    licenceUrl: '',
    source: 'https://commons.wikimedia.org/wiki/File:SweetPotato.jpg',
  },
  {
    key: 'syrup',
    label: 'Syrup',
    title: 'Rose syrup bottles.jpg',
    author: 'Sgconlaw',
    licence: 'CC BY-SA 4.0',
    licenceUrl: 'https://creativecommons.org/licenses/by-sa/4.0',
    source: 'https://commons.wikimedia.org/wiki/File:Rose_syrup_bottles.jpg',
  },
  {
    key: 'tabasco',
    label: 'Tabasco',
    title: 'Tabasco sauce.jpg',
    author: 'Andrew Dunn',
    licence: 'Public domain',
    licenceUrl: '',
    source: 'https://commons.wikimedia.org/wiki/File:Tabasco_sauce.jpg',
  },
  {
    key: 'tamarind',
    label: 'Tamarind',
    title: "Tamarind fruits (Tamarindus indica 'Si Thong').jpg",
    author: 'Ivar Leidus',
    licence: 'CC BY-SA 4.0',
    licenceUrl: 'https://creativecommons.org/licenses/by-sa/4.0',
    source:
      'https://commons.wikimedia.org/wiki/File:Tamarind_fruits_(Tamarindus_indica_%27Si_Thong%27).jpg',
  },
  {
    key: 'tanqueray',
    label: 'Tanqueray',
    title: 'Tanqueray bottle Gin.png',
    author: 'Bruce The Deus',
    licence: 'CC BY-SA 4.0',
    licenceUrl: 'https://creativecommons.org/licenses/by-sa/4.0',
    source: 'https://commons.wikimedia.org/wiki/File:Tanqueray_bottle_Gin.png',
  },
  {
    key: 'tea',
    label: 'Tea leaves',
    title: 'Ceylon black tea leaves.jpg',
    author: 'Patrick Kolencherry',
    licence: 'CC BY-SA 3.0',
    licenceUrl: 'https://creativecommons.org/licenses/by-sa/3.0',
    source: 'https://commons.wikimedia.org/wiki/File:Ceylon_black_tea_leaves.jpg',
  },
  {
    key: 'teachers',
    label: "Teacher's",
    title: "Teacher's Highland Cream 20cl bottle 1.jpg",
    author: 'IvanWalsh.com',
    licence: 'CC BY 2.0',
    licenceUrl: 'https://creativecommons.org/licenses/by/2.0',
    source: 'https://commons.wikimedia.org/wiki/File:Teacher%27s_Highland_Cream_20cl_bottle_1.jpg',
  },
  {
    key: 'tender-coconut',
    label: 'Tender coconut',
    title: 'Tender coconut image.jpg',
    author: 'Varunarivazhagan',
    licence: 'CC BY-SA 4.0',
    licenceUrl: 'https://creativecommons.org/licenses/by-sa/4.0',
    source: 'https://commons.wikimedia.org/wiki/File:Tender_coconut_image.jpg',
  },
  {
    key: 'tequila',
    label: 'Tequila',
    title: 'Tequila Don Julio.jpg',
    author: 'jlastras',
    licence: 'CC BY 2.0',
    licenceUrl: 'https://creativecommons.org/licenses/by/2.0',
    source: 'https://commons.wikimedia.org/wiki/File:Tequila_Don_Julio.jpg',
  },
  {
    key: 'tinned',
    label: 'Tins and cans',
    title: 'Konservendose-1.jpg',
    author: 'Rainer Zenz',
    licence: 'CC BY-SA 3.0',
    licenceUrl: 'http://creativecommons.org/licenses/by-sa/3.0/',
    source: 'https://commons.wikimedia.org/wiki/File:Konservendose-1.jpg',
  },
  {
    key: 'tissues',
    label: 'Tissue box',
    title: 'Tissue box.jpg',
    author: 'WikiGrower1',
    licence: 'CC BY 4.0',
    licenceUrl: 'https://creativecommons.org/licenses/by/4.0',
    source: 'https://commons.wikimedia.org/wiki/File:Tissue_box.jpg',
  },
  {
    key: 'toilet-cleaner',
    label: 'Toilet cleaner',
    title: 'ToiletcleanersbyAlofok (4).JPG',
    author: 'User:Alofok',
    licence: 'CC BY-SA 3.0',
    licenceUrl: 'https://creativecommons.org/licenses/by-sa/3.0',
    source: 'https://commons.wikimedia.org/wiki/File:ToiletcleanersbyAlofok_(4).JPG',
  },
  {
    key: 'toilet-roll',
    label: 'Toilet roll',
    title: 'Toilet paper roll.jpg',
    author: 'Cmann999',
    licence: 'CC BY-SA 4.0',
    licenceUrl: 'https://creativecommons.org/licenses/by-sa/4.0',
    source: 'https://commons.wikimedia.org/wiki/File:Toilet_paper_roll.jpg',
  },
  {
    key: 'tomato',
    label: 'Tomato',
    title: 'Tomato 2.jpg',
    author: 'Tshrinivasan',
    licence: 'CC BY-SA 3.0',
    licenceUrl: 'https://creativecommons.org/licenses/by-sa/3.0',
    source: 'https://commons.wikimedia.org/wiki/File:Tomato_2.jpg',
  },
  {
    key: 'tonic',
    label: 'Tonic water',
    title: 'Schweppes Indian Tonic Water (front).jpg',
    author: 'Reedy',
    licence: 'CC BY-SA 3.0',
    licenceUrl: 'https://creativecommons.org/licenses/by-sa/3.0',
    source: 'https://commons.wikimedia.org/wiki/File:Schweppes_Indian_Tonic_Water_(front).jpg',
  },
  {
    key: 'toor-dal',
    label: 'Toor dal',
    title: 'Pigeon pea (Red gram, Thuvarai in Tamil) 02.jpg',
    author: 'Nandhinikandhasamy',
    licence: 'CC BY-SA 3.0',
    licenceUrl: 'https://creativecommons.org/licenses/by-sa/3.0',
    source:
      'https://commons.wikimedia.org/wiki/File:Pigeon_pea_(Red_gram,_Thuvarai_in_Tamil)_02.jpg',
  },
  {
    key: 'triple-sec',
    label: 'Orange liqueur',
    title: 'Triple Sec.jpg',
    author: 'Chris Kirkman from Chapel Hill, North Carolina, United States',
    licence: 'CC BY 2.0',
    licenceUrl: 'https://creativecommons.org/licenses/by/2.0',
    source: 'https://commons.wikimedia.org/wiki/File:Triple_Sec.jpg',
  },
  {
    key: 'tuborg',
    label: 'Tuborg',
    title: 'Tuborg Green.jpg',
    author: 'McKaby',
    licence: 'CC BY-SA 3.0',
    licenceUrl: 'https://creativecommons.org/licenses/by-sa/3.0',
    source: 'https://commons.wikimedia.org/wiki/File:Tuborg_Green.jpg',
  },
  {
    key: 'turmeric',
    label: 'Turmeric',
    title: 'Turmeric rhizome.jpg',
    author: 'Schlawensko',
    licence: 'CC BY-SA 4.0',
    licenceUrl: 'https://creativecommons.org/licenses/by-sa/4.0',
    source: 'https://commons.wikimedia.org/wiki/File:Turmeric_rhizome.jpg',
  },
  {
    key: 'urad-dal',
    label: 'Urad dal',
    title: 'Urad dal black gram.jpg',
    author: 'தீப்தி செந்தில்',
    licence: 'CC BY-SA 4.0',
    licenceUrl: 'https://creativecommons.org/licenses/by-sa/4.0',
    source: 'https://commons.wikimedia.org/wiki/File:Urad_dal_black_gram.jpg',
  },
  {
    key: 'vermouth',
    label: 'Vermouth',
    title: 'Vermouth.jpg',
    author: 'Wikimedia Commons',
    licence: 'Public domain',
    licenceUrl: '',
    source: 'https://commons.wikimedia.org/wiki/File:Vermouth.jpg',
  },
  {
    key: 'vinegar',
    label: 'Vinegar',
    title: 'Synthetic vinegar bottles.jpg',
    author: 'Sgroey',
    licence: 'CC BY-SA 4.0',
    licenceUrl: 'https://creativecommons.org/licenses/by-sa/4.0',
    source: 'https://commons.wikimedia.org/wiki/File:Synthetic_vinegar_bottles.jpg',
  },
  {
    key: 'vodka',
    label: 'Vodka',
    title: 'Smirnoff Vodka bottle front.jpg',
    author: 'Alex P. Kok',
    licence: 'CC BY-SA 4.0',
    licenceUrl: 'https://creativecommons.org/licenses/by-sa/4.0',
    source: 'https://commons.wikimedia.org/wiki/File:Smirnoff_Vodka_bottle_front.jpg',
  },
  {
    key: 'water',
    label: 'Drinking water',
    title: 'Bottle of Water.jpg',
    author: 'Jiafei Slay Queen',
    licence: 'CC0',
    licenceUrl: 'http://creativecommons.org/publicdomain/zero/1.0/deed.en',
    source: 'https://commons.wikimedia.org/wiki/File:Bottle_of_Water.jpg',
  },
  {
    key: 'watermelon',
    label: 'Watermelon',
    title: 'Fresh Watermelons Stacked.jpg',
    author: 'PAULIX04',
    licence: 'CC BY-SA 4.0',
    licenceUrl: 'https://creativecommons.org/licenses/by-sa/4.0',
    source: 'https://commons.wikimedia.org/wiki/File:Fresh_Watermelons_Stacked.jpg',
  },
  {
    key: 'wheat-flour',
    label: 'Wheat flour (atta)',
    title: 'Wheat flour.jpg',
    author: 'Oliwier Brzezinski',
    licence: 'CC BY-SA 4.0',
    licenceUrl: 'https://creativecommons.org/licenses/by-sa/4.0',
    source: 'https://commons.wikimedia.org/wiki/File:Wheat_flour.jpg',
  },
  {
    key: 'whisky',
    label: 'Whisky',
    title: 'Bottle of whisky from the Scotch Malt Whisky Society.jpg',
    author: 'Paul Joseph',
    licence: 'CC BY 2.0',
    licenceUrl: 'https://creativecommons.org/licenses/by/2.0',
    source:
      'https://commons.wikimedia.org/wiki/File:Bottle_of_whisky_from_the_Scotch_Malt_Whisky_Society.jpg',
  },
  {
    key: 'white-rum',
    label: 'White rum',
    title: 'Bacardi Carta Blanca Rum 01.jpg',
    author: 'Indrajit Das',
    licence: 'CC BY-SA 4.0',
    licenceUrl: 'https://creativecommons.org/licenses/by-sa/4.0',
    source: 'https://commons.wikimedia.org/wiki/File:Bacardi_Carta_Blanca_Rum_01.jpg',
  },
  {
    key: 'white-wine',
    label: 'White wine',
    title: 'Muscadet wine bottle.jpg',
    author: 'Julien.scavini',
    licence: 'CC BY-SA 4.0',
    licenceUrl: 'https://creativecommons.org/licenses/by-sa/4.0',
    source: 'https://commons.wikimedia.org/wiki/File:Muscadet_wine_bottle.jpg',
  },
];
